### ISSUE TITLE
Iphone wallet app not working...

### ISSUE THREAD

**Issue by arvind9** [dagcoin/dagcoin#1003]
## Expected Behavior
 You should make proper app or ios i have tried so many ways with your dagcoin-osx64.dmg but nothing working or install app on ios

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fishera123** [comment]
or you can try our web wallet version. https://wallet.dagcoin.org/
