### ISSUE TITLE
message should be displayed in addressbook if there is no addresses.

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1008]
## Expected Behavior

```you don't have any contacts in your address book``` message should be displayed if user doens't have any addresses.
## Current Behavior

empty popup 
![Screen Shot 2018-04-04 at 7.02.58 PM.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/43a4a45e-c6c9-4f96-848d-eab8f23b8d1a)

## Steps to Reproduce (for bugs)

1.go to send screen
2.click on address book.
3.empty address book popup is displayed

## Your Environment

* Version used:1.4.5
* Operating System and version (desktop or mobile):All

**Comment by msinansahin** [comment]
fixed in #978

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/38484786-611793d4-3be0-11e8-9840-ffeaf8f11128.png)

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/38488909-7fcfe80a-3bed-11e8-9ab8-f9f6e26f5f76.png)
