### ISSUE TITLE
user should be able to change hub from settings 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1009]
## Expected Behavior

user should be able to change hub manually in case of emergency. 

<img width="950" alt="hubsettings" src="https://user-images.githubusercontent.com/35455231/38356454-75018348-38c8-11e8-8fe1-b002adb5991f.png">

## Current Behavior

hub is hardcoded in wallet
## Possible Solution

add options in global settings 

## Your Environment

* Version used:1.4.5
* Operating System and version (desktop or mobile):All

**Comment by irinadoros** [comment]
User can switch on unexisting hub. Then he can see the notification about hub connection - OK
![image](https://user-images.githubusercontent.com/35455231/39182129-8f4008a0-47c4-11e8-9a1b-c7a18728107e.png)
