### ISSUE TITLE
Payment request from Chat is broken

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1018]
Payment request from Chat is broken if it sent from old version (for example 1.4.4)

## Steps to Reproduce (for bugs)
1. Go to paired devices
2. Send payment request from Chat
3. Received request is not correct sentence what is clickable - NOK

![image.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/fcb19bb3-2cc6-4702-8958-670a570eb4d9)

## Your Environment
* sender or receiver: testnet +task-999 (ver 1.4.5)
* receiver or sender: ver 1.4.4
* Windows 10
* Android 8

## Expected Behavior
* Payment request from chat is clickable also in case if it came from old app version like 1.4.4
* Sentence is correct

**Comment by dkostenevich** [comment]
Can't reproduce
