### ISSUE TITLE
Instead of light wallet full wallet is created

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1032]
Instead of light wallet is created full wallet.

## Steps to Reproduce 
Initial run
Recommended settings (light wallet) - sometimes create full wallet

Wallet address: BIAQ3NDO2GOED7AZUIH6IJFCE2MJEPNH
Device address: 0FAUNRSXN27HCWBD5JCTDHWJWVISQTVFH

![image.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/74b4b3aa-f794-4108-9fad-b2acfe45afba)

## Your Environment
devnet
windiws 10

## Expected Behavior
* If user creates light wallet, then light wallet is created

**Comment by msinansahin** [comment]
The problem was, in index controller.
autorefreshservice was standing up after one minute. If the user waits at the phase of creating initial wallet, full wallet is created.
