### ISSUE TITLE
Devnet: charging money doesn't work well

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1033]
Money charge doesn't work well:
* on the Home page the is no money visible
* money are visible in advanced "Wallet information"

## Steps to Reproduce
1. DAGs download on the new wallet: http://faucet.dagcoin.org/0XG53O7DCGICBKEYH4ILMYZZHJNI2AIBQ/JSRAFJNLYG624OYQMHHE6W2LP7DY5MUA/d
2. Open wallet on Home page -> the amount is 0 DAG and nothing in pending status
3. Hamburger menu
4. Click on the three dots near the wallet
5. Advanced
6. Wallet information
7. Check BALANCE BY ADDRESS

<img width="649" alt="devnetfauset" src="https://user-images.githubusercontent.com/35455231/38484084-fd8cc728-3bdd-11e8-8040-e1ef317a020f.png">

## Your Environment
* devnet
* Windows 10

## Expected Behavior
Home page shows money, if wallet has money

**Comment by dkostenevich** [comment]
This is not a bug. 
We should to use https://testnetexplorer.dagcoin.org/faucet/<DEVICE_ADDRESS>/<ADDRESS>/b for devnet branch.
