### ISSUE TITLE
New version wallet says Uncaught error and closing after pressing OK button . can't use it Dagcoins is locked 

### ISSUE THREAD

**Issue by SMarkevich** [dagcoin/dagcoin#1038]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by SMarkevich** [comment]
![03042018](https://user-images.githubusercontent.com/19611792/38528133-2ae60fcc-3c56-11e8-9917-d1d220d84da4.JPG)

**Comment by SMarkevich** [comment]
Dear dagcoin team . your new version  wallet is not working ! Can you please fix the error or at least send the 609 dagcoin from wallet back to daguniversity account 

FN635FBYJJTMYM54SC6XYBGWNZ2F75GM       Dagwallet 

0QTLG2GWAB7LYX4YQTVBJ5QM76UMLFBPW      device number 

Paafy                                                                   daguniversity account

wallet says Uncaught error and closing straight after pressing OK button

**Comment by SMarkevich** [comment]
dag support doing nothing ! Ignoring all messages !

**Comment by fishera123** [comment]
Hi, we are aware of your problem, from the support team. We are fixing you problem.

**Comment by SMarkevich** [comment]
and eventually  it is happened again :( 
![default](https://user-images.githubusercontent.com/19611792/38614021-99aa2e56-3d83-11e8-97fd-cbebded37c17.JPG)

**Comment by SMarkevich** [comment]
I've tried to reinstal it 4 times at least.. 
![default](https://user-images.githubusercontent.com/19611792/38614090-db394bcc-3d83-11e8-9bf9-a787085be421.JPG)

**Comment by irinadoros** [comment]
Please download new version 1.4.5.

**Comment by SMarkevich** [comment]
Hello! i wish to.. but can you send me a link . Because official dagcoin
website provide only 1.4.4 light wallet and nothing else

**Comment by SMarkevich** [comment]
i've installed the new version and nothing has changed
![dag145](https://user-images.githubusercontent.com/19611792/38779055-f5568ce2-40ba-11e8-96bb-5dd80411d4fb.JPG)

**Comment by SMarkevich** [comment]
i've installed the new version and nothing has changed
![Uploading dag145.JPG…]()

**Comment by SMarkevich** [comment]
Is anybody help me with this issue ever ???????????

**Comment by irinadoros** [comment]
User problem is fixed.
