### ISSUE TITLE
CSV extract shows "Moved" transaction amount as zero

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1054]
CSV extract shows "Moved" transaction amount as zero. Actually money is moved from one local address to another and it should be visible for user.

## Steps to Reproduce
* Send money inside your wallet from one address to another

<img width="825" alt="exporttocsvdevnet" src="https://user-images.githubusercontent.com/35455231/38730967-4cf00f14-3f21-11e8-996b-63784785e2f6.PNG">

## Your Environment
* devnet

## Expected Behavior
* Extract shows all transactions

**Comment by msinansahin** [comment]
The amount should already be 0. But while exploring this issue, a bug was found. 
In linux moved transactions are not seen properly. It is fixed.

**Comment by irinadoros** [comment]
Retested in devnet. Everything is correct. My mistake.
