### ISSUE TITLE
User can not send all money what he has in wallet

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1056]
User can not send all money what he has in wallet. It seems like problem is because of fee amount.

## Steps to Reproduce (for bugs)
1. Go to Send page
2. Click Send all
3. Scan the receiver address
4. Send
Notification appear

![SendAllDevnet3.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/0ee9ead0-77a4-4054-aa17-9255f222966a)
![SendAllDevnet2.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/efaa2798-8cbb-4c4e-90e7-588be4a52c65)

## Your Environment
devnet

## Expected Behavior
* User can send all money from wallet

**Comment by msinansahin** [comment]
Could not reproduce. Could you please test again?
