### ISSUE TITLE
Dagcoin app fails on the first start

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#106]
With the following error: 'Failed to switch to light, please restart the app'
See src/js/controllers/splash.js, line 38.
The missing configuration is being written to the local configuration file in line 35. The fact that such configuration is not found/loaded properly is strange: byteballcore/conf.js looks into such local file.
There has been an update in byteballcore.js: it could be useful to have a look what it changed.

**Comment by yaryribero** [comment]
Tried locally: The issue still happens

Try deleting the configuration directory and repeat the test

**Comment by fishera123** [comment]
@vkolt go to ```~/Library/Application Support/``` , remove dagcoin database and then start the wallet. if it starts without errors it is fixed.
