### ISSUE TITLE
please update the wallet on official website to 1.4.5  or send a link . there is still 1.4.4 which is impossible to use. Thank you

### ISSUE THREAD

**Issue by SMarkevich** [dagcoin/dagcoin#1062]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by SMarkevich** [comment]
Is anybody help me with this issue ever ???????????

**Comment by fishera123** [comment]
hi, can you send us your wallet backup somehow? and we will fix it. Maybe you can send it to support and then they will send it to us. Thanks

**Comment by uluaiv** [comment]
This fix, as the bug, only affects testnet.

**Comment by fishera123** [comment]
@uluaiv can we patch this fix and release new version of the wallet? This week?

**Comment by uluaiv** [comment]
Give the fix a positive review, move it to test and the magic might happen :)

**Comment by SMarkevich** [comment]
Hi Fishera ! thank you for taking action . I've send the backup and video file showing how the wallet working to support ... Let me know if anything else i can help to.. Thank you very much ..!

**Comment by SMarkevich** [comment]
If support didn't create the ticket still ...
![backup](https://user-images.githubusercontent.com/19611792/38936473-c7317b3c-4318-11e8-957f-f71a0a87e8c1.JPG)

**Comment by fishera123** [comment]
Please remove this photo. You are publishing sensitive information.

**Comment by paafy** [comment]
Can’t do it through the phone .. you can’t delete it yourself..!?

**Comment by fishera123** [comment]
@SMarkevich we will upload new package here. Please try it and give us feedback
