### ISSUE TITLE
Merchant Payment Workflow Update

### ISSUE THREAD

**Issue by uluaiv** [dagcoin/dagcoin#1079]
From Priit Kallas:

1) when you fetch the invoice info from Dagpay API, the response will include a "publicId" attribute which is a 36-character uuid v4 (just as the normal "id" that is currently used)
2) you will include this "publicId" instead of the current "id" in the payment unit

that should be all so a very minor change on your side

when the app now calls the payment unit updated, the payment unit info will be fetched and Dagpay will search for the invoice by the public id rather than the actual invoice id

## Expected Behavior
About a merchant payment:
The real public id used internally should be hidden.
Only an unimportant id for retrieval should be publicly available

## Current Behavior
Only one general public id is available

## Possible Solution
This needs to be implemented and delivered to the devnet as a change

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by irinadoros** [comment]
* receiver address is open for change - NOK
![image](https://user-images.githubusercontent.com/35455231/39351168-59d30716-4a09-11e8-92b4-881dcc77c31b.png)

**Comment by irinadoros** [comment]
* The real public id used internally should be hidden - OK
* Only an unimportant id for retrieval should be publicly available - OK
* local branch - OK
* devnet - OK
