### ISSUE TITLE
Introduction to the new way

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1115]
Introduction to the new way

<img width="1112" alt="initialrun2" src="https://user-images.githubusercontent.com/35455231/39112127-32c8f04e-46e0-11e8-9632-07ead03eec4b.png">

## Environment
* Devnet

## Expected Behavior
* User sees notification about money migration
* New view is before last view "Start sending dagcoin"
* [Contact support] button redirect to email writing with filled address info@dagcoin.org
* "I understand. Go to wallet." is link wich opens view "Start sending dagcoin"
* "Contact support" will gone if user has some amount in wallet
* different name in package json
* address prefix should be changed

**Comment by rasmusliiva** [comment]
Icon used: [transfer-2.svg.zip](https://github.com/dagcoin/dagcoin/files/1937319/transfer-2.svg.zip)
