### ISSUE TITLE
Popup with notification about sending money

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1122]
Popup with notification about sending money.

## Expected Behavior
* Every time when user opens Home page, the popup appear
* User can just close this notification with cross
* User can click "I understand. Don't show this message again." and notification will not appear anymore.
* User can write to support, by clicking [Contact support]
* info@dagcoin.org

## Your Environment
* testnet

**Comment by fishera123** [comment]
Created #1131 which should be implemented after this task.

**Comment by irinadoros** [comment]
Every time when user opens Home page, the popup appear - OK
User can just close this notification with cross - OK
User can click "I understand. Don't show this message again." and notification will not appear anymore. - OK
User can write to support, by clicking [Contact support] - OK
info@dagcoin.org - OK

**Comment by irinadoros** [comment]
Cross is visible for notification closing - OK
<img width="486" alt="testnetnotification" src="https://user-images.githubusercontent.com/35455231/39670651-328a4934-5112-11e8-9c19-bc90ad8b2304.png">

**Comment by irinadoros** [comment]
Will not go to LIVE
