### ISSUE TITLE
DAg Client should connect to the Dagcoin hub

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1123]
DAg Client should connect to the Dagcoin hub

**Comment by sabahang** [comment]
this ticket was also merged into 1122, so can be ignored

**Comment by irinadoros** [comment]
Connected to the spoon - OK

**Comment by sabahang** [comment]
@irinadoros spoon? This hub is for live old wallet! the address of the hub is wss://explorer.dagcoin.org/wss/

**Comment by irinadoros** [comment]
Will not go to LIVE
