### ISSUE TITLE
Undefined error message

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#113]
Tried to send transaction, but received error message: Could not send payment: undefined

Message is unclear, can not understand why payment can not be sent. 

Guess: I have unconfirmed transaction and money is blocked

**Comment by vkolt** [comment]
![Screen Shot 2017-07-17 at 19.18.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f46b7191a379e60c2a59415e4bbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec858f54be94853a11b3562f43b.png)

**Comment by fishera123** [comment]
when I have unconfirmed funds i received error -> 
<img width="381" alt="screen shot 2017-07-19 at 4 02 27 pm" src="https://user-images.githubusercontent.com/9304560/28368044-b8d4e898-6c9b-11e7-9d79-f8cf07e4f6fe.png">

**Comment by fishera123** [comment]
@vkolt when you will test it can you also show me send me your console pictures?

**Comment by vkolt** [comment]
![Screen Shot 2017-07-19 at 17.29.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455fa6b7191a379e80c2958415a4abe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f33aa984ec858f24ce54b51a21a3064f43b.png)

**Comment by fishera123** [comment]
Can you reproduce it?

**Comment by vkolt** [comment]
yes, it is still present on my computer

**Comment by iaptsiauri** [comment]
The problem was 

> No bytes to pay the fees 
I have submitted the PR #124 to fix this issue, @vkolt and @fishera123 git it a try
