### ISSUE TITLE
Hub should be able to send clients instructions of migrating to new network

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1131]
## Expected Behavior

Add event in the hub which will fire event about migrating coins to new network. On the other side we need an event listener inside client, which will display notification that came from hub.

**Comment by msinansahin** [comment]
Related PR: https://github.com/dagcoin/dagcoin-hub/pull/1

**Comment by irinadoros** [comment]
Should test together with #1122

**Comment by irinadoros** [comment]
Will not go to LIVE
