### ISSUE TITLE
Enable different versions of dagcoin works at the same time in the same device

### ISSUE THREAD

**Issue by msinansahin** [dagcoin/dagcoin#1135]
Enable core gets folder name from environment. It is the clue.

## Expected Behavior
Enable different versions of dagcoin works at the same time in the same device

## Your Environment
devnet

**Comment by msinansahin** [comment]
different name in package json or get name from ENV.
address prefix should be changed

**Comment by msinansahin** [comment]
dagcoin folder is created y nwjs. So that, in order to run multiple instances at the same time developers must change the package.json name property.

**Comment by msinansahin** [comment]
@fishera123 in order to install old and new wallet in android the package name of dagcoin is needed to be changed.

Current package name is `org.dagcoin` (there is no difference live and test)

Proposed package name `org.dagcoin.wallet` and `org.dagcoin.wallet.tn`

**Comment by irinadoros** [comment]
* two applications runs on the same device at the same time - OK
* transactions are created and confirmed - OK
