### ISSUE TITLE
Scroll issue on windows

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#114]
windows app still has two scroll bars. One of them is not working and present on every page

There is one grey line on top of page, look like horizontal scroll bar

**Comment by fishera123** [comment]
fixed in #73

**Comment by fishera123** [comment]
depends on #137

**Comment by fishera123** [comment]
test it in new design

**Comment by vkolt** [comment]
![Screenshot (21).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0fa1dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ed3924e68b8e4b3d1e000ac4.png)

**Comment by vkolt** [comment]
![Screenshot (22).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0fa2dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ed3924e68b8d473a1c060ac4.png)

**Comment by fishera123** [comment]
@vkolt we cannot fix upper one it is coming from nw.js
