### ISSUE TITLE
"Pay to this address" chat functionality remembers previous transaction amount

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1156]
"Pay to this address" chat functionality remembers previous transaction amount

## Current Behavior
User chooses some chat. User clicks on received via chat address and chooses "Pay to this address". User is redirected to Send page, where amount SHOULD BE EMPTY. Now it is filled with the previous transaction amount.

## Steps to Reproduce
1. Go to Chat
2. Open some chat
3. Click on the [+]
4. Choose "Insert my address" and send it
5. On the other device open same chat
6. Click on this received address
7. Click "Pay to this address" -> user will be redirected to the Send page

![PayToThisAddress.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/d4935d9a-a2b0-40dd-bce1-f01b4728f15b)

## Your Environment
* devnet

## Expected Behavior
* Amount field is empty on Send page, if user came from "Pay to this address" link

**Comment by msinansahin** [comment]
will be fixed in #1154

**Comment by irinadoros** [comment]
* Amount field is empty on Send page, if user came from "Pay to this address" link - OK
* local branch
