### ISSUE TITLE
Branch name change

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1162]
## Current Behavior
Windows has Dagcoin, linux has Dagcoin Wallet and os x has dagcoin-wallet.
I supposed “Dagcoin Wallet” would be good

## Your Environment
devnet

## Expected Behavior
* "Dagcoin Wallet" and "Dagcoin Tn Wallet"
* Android package names are org.dagcoin.client and org.dagcoin.client.tn

**Comment by msinansahin** [comment]
Application names for 2.0.0 version
Live: Dagcoin Wallet
Test: Dagcoin Tn Wallet
