### ISSUE TITLE
Styles for toggle controls

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1170]

**Comment by dkostenevich** [comment]
parts of this task will be completed in #1166

**Comment by irinadoros** [comment]
Toggle control for react version needs a little bit more shadow. In old app they are more comfortable.
<img width="663" alt="togglebutton" src="https://user-images.githubusercontent.com/35455231/39925002-a8e05eec-5532-11e8-88e3-920c9c4c1a68.PNG">

**Comment by irinadoros** [comment]
Toggle buttons are nice - OK
![image](https://user-images.githubusercontent.com/35455231/40042701-ee1c1564-582a-11e8-8bb0-9b5c1515ee8f.png)
