### ISSUE TITLE
Edit contact in address book

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1171]

**Comment by irinadoros** [comment]
1. Go to existing contact
2. Clickto three dots
You will see Edit and Delete links. Design is different in react and old app:
<img width="663" alt="contactedit" src="https://user-images.githubusercontent.com/35455231/39927469-fa1d7030-553a-11e8-93c6-243d1e6ced69.PNG">

**Comment by dkostenevich** [comment]
Popup not in the scope of this task. (i'm added this popup for navigation beetwen screens)

**Comment by irinadoros** [comment]
Small issue about intermediate screen is described in another ticket.
Edit contact view is nice - OK
