### ISSUE TITLE
sign mac package with certificate

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#118]

**Comment by fishera123** [comment]
testing steps: 
* make sure that you only allow applications downloaded from the store and verified developers. Go to system preferences -> Security & Privacy -> General. you will see Allow apps downloaded from the menu item. Mac App Store and identified developers should be checked. 
* go to dagcoin releases and download Mac package.
* Package should be opened without warning that it is from the unindefied developer.

**Comment by vkolt** [comment]
![Screen Shot 2017-07-20 at 20.50.10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f36b7191a37aef0c2e51415e4ebe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f33aa984ec858f34ce24c51ac1a3560f43b.png)

**Comment by vkolt** [comment]
Should I see this message?

**Comment by fishera123** [comment]
yes

**Comment by fishera123** [comment]
you shouldn't see this https://www.google.ee/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwixq4uc05jVAhWoHJoKHfd-C9MQjRwIBw&url=http%3A%2F%2Fwww.iclarified.com%2F28180%2Fhow-to-open-applications-from-unidentified-developers-in-mac-os-x-mountain-lion&psig=AFQjCNGsqFtTRii6-un58hJXdu_Im6cXuQ&ust=1500667227060916
