### ISSUE TITLE
Dagcoin is NOT a Ponzi Pyramid Scam

### ISSUE THREAD

**Issue by cryptoshaune** [dagcoin/dagcoin#1228]
Anyone referring to Dagcoin as the Dagcoin scam - sincerely has it all wrong. The evidence is way to strong to the contrary including the simple fact that we can watch the actual coin being built here on www.github.com Although it is early (great timing to buy a hot young coin) - and there are pieces of the Dagcoin ecosystem yet to be fully delivered they are coming and coming fast.

A Ponzi doesn't have a real product of real value - so others before Dagcoin who didn't actually have a coin can be referred to as a Ponzi Pyramid Scam - but not Dagcoin. There's more to say but rather than lay it all out here - I've already mapped out a full balanced Dagcoin review here...

www.thedagcoinscam.com

**Comment by alidino** [comment]
Your Independent Analysis please...

**Comment by AbdulazizElhousseiny** [comment]
The link doesn't work, i can't read your review

**Comment by flkrr** [comment]
Shaune Clarke, owner of thedagcoinscam.com, is just another scammer. He took his website offline when even he could no longer act as if Dagcoin is not a scam.

He was just another pimp trying to scam you into Dagcoin. With his website he did a poor effort to 'prove' that Dagcoin is not a scam by using fallacys, lies and slander to people trying to warn you for the Dagcoin scam.

Dagcoin is just a pyramid scam, nothing more. Don't be guillible. Just ignore Dagcoin. The scam is already dead in the water anyways.

**Comment by 3alaKivy** [comment]
القائمون على العُملة يدغدغون مشاعر العرب على الوتر الذي يُحبون.
الشخص الذي طرح القضية شخص مجهول، وأصحاب المشروع الى الان لم يردوا بشكل رسمي.
وفي انتظار التعرف على هوية القائمين على تطوير المشروع.

هذا الرد مقصود أن يكون باللغة العربية.
This comment is intended to be in Arabic.
