### ISSUE TITLE
"Set fingerprint when password is active" functionality is broken

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1232]
"Set fingerprint when password is active" functionality is partly broken. 
When pwd credentials are active and user just activate fingerprint credentials, then for 10-15 seconds both credentials are active. After that time app asks fingerprint and pwd and pdw deactivates. It should be as one flow without delay. It was working like that!

## Steps to Reproduce
1. Go to settings
2. Security
3. Check, that set password option is active
4. Enable option scan Fingerprint 
5. Touch sensor
6. Confirm fingerprint: touch sensor
7. Enter you password for deactivation
8. Fingerprint authentication
Expected: Fingerprint request is set up, password request is switched off
As Is: Fingerprint and Pwd are activated

![screenshot_20180514-145413](https://user-images.githubusercontent.com/35455231/39996809-69dec0f4-5789-11e8-9a08-277ccaef10ef.jpg)
![screenshot_20180514-145422](https://user-images.githubusercontent.com/35455231/39996815-6d638656-5789-11e8-85d1-d553aaa5545f.jpg)
![screenshot_20180514-145433](https://user-images.githubusercontent.com/35455231/39996819-71cd8e80-5789-11e8-8464-b553fe38d1db.jpg)

## Your Environment
devnet

## Expected Behavior
* Fingerprint request is set up, password request is switched off

**Comment by msinansahin** [comment]
Fixed in #1229
