### ISSUE TITLE
[Make new payment] button should be red, not blue

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1246]
[Make new payment] button should be red, not blue

## Steps to Reproduce 
1. Go to Home page
2. Open details of some transaction
User can see there blue button [Make a new transaction]
![image.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/c197ecf9-3bdf-4a67-8fd9-27d4a8b758fa)

## Your Environment
devnet

## Expected Behavior
* Button color is red

**Comment by msinansahin** [comment]
Fixed in 1247

**Comment by rasmusliiva** [comment]
![dagcoin_transactiondetails2 copy](https://user-images.githubusercontent.com/37702190/40163568-d3af8760-59bf-11e8-8403-d241f21cf24a.jpg)


icon: 
[up-arrow.svg.zip](https://github.com/dagcoin/dagcoin/files/2012132/up-arrow.svg.zip)

**Comment by irinadoros** [comment]
In local branch - OK
![image](https://user-images.githubusercontent.com/35455231/40222289-b1149c68-5a87-11e8-87eb-cc87c8871036.png)
