### ISSUE TITLE
undefined conf in full wallet

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#126]
![image](https://user-images.githubusercontent.com/9304560/28534982-72e437c6-70ab-11e7-9ec1-229bd86ee11e.png)

**Comment by vkolt** [comment]
![Screen Shot 2017-07-27 at 20.04.00.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246456f46b7191a37aef0c2b55415f4ebe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f33aa984ec859f74ce44c56a1103e62f43b.png)

**Comment by vkolt** [comment]
hope it is the same error. Go to  Settings -> Global preferences ->Backup wallet seed and after that click back button
