### ISSUE TITLE
move testnet servers to pm2 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1263]
## Expected Behavior

use pm2 instead of forever

**Comment by msinansahin** [comment]
pm2 application configuration json file is as follows

[{
  "name"       : "testnet-explorer",
  "script"     : "explorer/explorer.js",
  "pid_file"  : "/home/experimental/.pm2/pids/testnet-explorer.pid",
  "exec_mode"  : "cluster",
  "watch"     : true,
  "autorestart" : true,
  "instances" : 1
}, {
  "name"       : "testnet-witness-1",
  "script"     : "witness-1/start.js",
  "pid_file"  : "/home/experimental/.pm2/pids/testnet-witness-1.pid",
  "exec_mode"  : "cluster",
  "watch"     : true,
  "autorestart" : true,
  "instances" : 1
}, {
  "name"       : "testnet-witness-2",
  "script"     : "witness-2/start.js",
  "pid_file"  : "/home/experimental/.pm2/pids/testnet-witness-2.pid",
  "exec_mode"  : "cluster",
  "watch"     : true,
  "autorestart" : true,
  "instances" : 1
}, {
  "name"       : "testnet-hub",
  "script"     : "hub/start.js",
  "pid_file"  : "/home/experimental/.pm2/pids/testnet-hub.pid",
  "exec_mode"  : "cluster",
  "watch"     : true,
  "autorestart" : true,
  "instances" : 1
}]
