### ISSUE TITLE
investigate android client error.

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#127]
one of our users downloaded a Dagcoin app for Android smartphone and it doesn't seem to function. Unable to launch an app. Getting a notification - Unfortunately, Dagcoin has stopped. 
![image](https://user-images.githubusercontent.com/9304560/28535113-d4ec78a2-70ab-11e7-86cc-84dc90066f52.png)

**Comment by vkolt** [comment]
Tested on Android 7.0 and 6.0.1 - application working fine
Tested on Android 4.1.2 - not possible to download from play market as not supported 
Can not reproduce problem

**Comment by fishera123** [comment]
closing for now
