### ISSUE TITLE
Sending address functionality (chatbot) give not correct message and error at exit

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#130]
Insert my address from one device
Check message on another (message itself does not look correct)
Offer a contract link gives error
Close chatbot (this action gives error)

**Comment by vkolt** [comment]
![Screenshot (7).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ab9d665043761260ea62864c7b96aea1b2f58585f4dfd1450594df5ad892ba4b06f2483590ab9c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1e83d27e7898f4d39181755.png)

**Comment by dkostenevich** [comment]
fixed in #139

**Comment by vkolt** [comment]
message for receiver  still looks bad

**Comment by vkolt** [comment]
Do we really need contract functionality ? If yes, what it is and how it is working

**Comment by dkostenevich** [comment]
fixed in branch issue-143 #150

**Comment by dkostenevich** [comment]
> Do we really need contract functionality ? If yes, what it is and how it is working
Question not for me :)
