### ISSUE TITLE
Request a payment functionality in chatbot  gives error and closes application

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#131]

**Comment by dkostenevich** [comment]
fixed in #139

**Comment by vkolt** [comment]
![Screenshot (13).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca3dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d87b0b68b49c0e93b25ee8c864d381b0c0ac4.png)

**Comment by vkolt** [comment]
receiver gets error if sender request payment

**Comment by dkostenevich** [comment]
fixed in branch issue-143 #150

**Comment by vkolt** [comment]
Can not request  not an integer amount of Dagcoins

**Comment by vkolt** [comment]
When receiver clicks on request message, he redirected to send page which is prefilled by requested amount. But amount itself is not correct (for example if you request 5 bytes it prefilled with 5 Dagcoins, or if you request 5 Dagcoins it prefilled with 0.000005 Dagcoins )

**Comment by dkostenevich** [comment]
fixed, can be tested in issue-157 brunch
