### ISSUE TITLE
Android suggests password for full backup fail creation

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1314]
Full backup password field is a text, not pwd type. Android suggests password for backup when used visible mode for characters.

## Steps to Reproduce 
1. Go to settings 
2. Choose Security
3. Choose Backup wallet
4. Choose Full backup
5. Set valid matching passwords -> android suggest pwd
6. Click export 
Expected: 
* success message appears (notification in black box) and file is loaded 
* ringbell notification appears to modal window and ringbell icon is changed

![fullbackup](https://user-images.githubusercontent.com/35455231/40544826-3ac24064-6032-11e8-9a93-b9a715817bc4.jpg)

![screenshot_20180525-160116](https://user-images.githubusercontent.com/35455231/40545637-3470cae8-6035-11e8-934d-a386e7bfb887.jpg)

## Your Environment
devnet

## Expected Behavior
* Android doesn't suggest password

**Comment by msinansahin** [comment]
disable/enable while toggling visibilty

**Comment by irinadoros** [comment]
* disable/enable while toggling visibilty - OK
