### ISSUE TITLE
[Clear notifications] button should be changed to link in the same style what we already use id app

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1316]
Clear notifications button should be changed to link in the same style what we already use id app

![ClearNotification.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/54738f8f-468e-416f-8355-fd1c00e782df)

## Steps to Reproduce 
1. Go to Home page
2. Click on the notification ring bell icon
There is blue button [Clear notifications], it should be changed.

## Your Environment
devnet

## Expected Behavior
* In the Notifications modal window user can see link "Clear notifications" in same style like "Make new payment"

**Comment by irinadoros** [comment]
Ask for icon!

**Comment by fishera123** [comment]
used the same icon from clear chat history.
