### ISSUE TITLE
Recovery from full backup doesn't work well on mobile device

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1323]
Recovery from full backup doesn't work well on mobile device

## Current Behavior
* After file and pwd inserting, app said that recovery was successful please restart app
* after restart nothing is recovered, only empty wallet
* sometimes recovery works well
* don't have this problem on desktop version

## Your Environment
devnet 2.1.0

## Expected Behavior
* Recovery from full backup works well on mobile device

**Comment by msinansahin** [comment]
Fixed in #1326

**Comment by irinadoros** [comment]
I cannot recover wallet on windows 10 from desktop wallet backup wich was created on Linux - NOK
![image](https://user-images.githubusercontent.com/35455231/40766272-a3147748-64b7-11e8-8474-a26ac2281c68.png)

**Comment by irinadoros** [comment]
Recovery from full backup works well on mobile device - OK
