### ISSUE TITLE
Bytball.org inside pairing link for chatbot

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#133]
Not sure if it is correct or we should use something as dagcoin?

**Comment by dkostenevich** [comment]
Currently we can't change byteball.org to dagcoin.org.
byteball.org is a hub and we using it.
We can change name after moving to our hub.

**Comment by yaryribero** [comment]
We can have our hubs but nothing forbids to use byteball.org, as we are based on them
