### ISSUE TITLE
During wallet opening user can see empty and small red bar on Home page - not typical view for Home

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#1331]
During wallet opening user can see empty and small red bar on Home page - not typical view for Home. Please lets do like this:
* When wallet is opening lets show to user spinner
** When Amount and transaction exist, then after download lets show it
** When Amount and transactions doesn't exist, then "Buy dagcoin" view 

![WalletOpening.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/081944a7-338b-4060-8b4d-8631c223b632)

## Steps to Reproduce

1. Go to Home page
2. Switch to another wallet 
3. Open app
In all this cases this small red bar exist.

## Your Environment
devnet 

## Expected Behavior
* When user open wallet, then first view is with downloading spinner. 
* "Buy Dagcoin" view will appear if wallet doesn't have any transactions
* If data exist, then user will see after data download amount and transactions list

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/40792208-0a0fc58e-6502-11e8-8e18-c34b7413aa75.png)

**Comment by irinadoros** [comment]
Multidevice wallet creation: wallet said "Updating wallet" and nothing happen. After restart wallet is correct. On mobile I have devnet version and "Buy dagcoin" view is appeared. - NOK
![image](https://user-images.githubusercontent.com/35455231/40792818-84721416-6503-11e8-9126-e3b606d5991d.png)

**Comment by dkostenevich** [comment]
Can't reproduce after latest fix

**Comment by irinadoros** [comment]
* when user switch between wallets, then Home page visual is correct. Red bar doesn't change size, only data came later - OK

**Comment by irinadoros** [comment]
Multidevice wallet creation and delete is OK
Plain wallet creation and delete is OK
Switch wallet to another wallet is OK
Visual don't jump and seems smooth - OK
