### ISSUE TITLE
No scroll in chatbot message field

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#134]
If the message is long enough, there is no possibility to scroll to the top. 
We should limit the text or add possibility go to the top of the message

**Comment by vkolt** [comment]
![Screenshot (8).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec05b9d665043761260ea62864c7b96aea1b2f58585f4dfd1450594df5ad892ba4b06f2483590ab9c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc1e83d26e3888b4b3c161755.png)

**Comment by dkostenevich** [comment]
#139
