### ISSUE TITLE
Chat recording drop-down menu nonfunctioning

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1347]
Precondition: 
Must have a paired device.

Steps to reproduce:
1. Select 'Paired Devices' from dag wallet menu
2. Select paired device
3. Click on 'chat recording' ON

Result: 
After selecting chat recording option drop-down menu will appear, but the user is not able to change any options and the text is not fully visible.
A slider is visible after a drop-down menu appears but the slider is nonfunctioning.

Expected result: 
The drop-down menu should be centered or the slider should be functioning.

Step 1
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/6c3f5d73-94ce-4e9e-b75b-b9349a2a6ae1)

Step 2 
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/d9ed1181-f1c3-4e74-9628-f0f95d18452a)

Step 3 
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/16de8dce-6586-41f0-b009-1d9baf70c7cd)

**Comment by irinadoros** [comment]
* The drop-down menu should be centered or the slider should be functioning. - OK
![image](https://user-images.githubusercontent.com/35455231/41103091-014d1874-6a71-11e8-9dab-303964d8d4ce.png)
