### ISSUE TITLE
RECOVERY submits both inputs

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1348]
Open dag Wallet
Open RECOVERY under SECURITY.
Select "RECOVER FROM BACKUP" tab.
Choose a file
Click IMPORT.
RESULT: Error appears: "Incorrect password or file", if you change tab to recover from seed, then you can see the same error message above YOUR WALLET SEED input.

![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/2dddc54a-f1d8-4e20-b2c5-b72356d0c4d3)

![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/05409829-01f7-45fb-95f6-1cc6fd18274b)

**Comment by irinadoros** [comment]
* Seed view doesn't show wrong pwd notification if it was on full backup recovery view - OK
