### ISSUE TITLE
Cannot remove paired devices

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#1349]
Precondition: 
Must have a paired device.

Steps to reproduce:
1. Select 'Paired Devices' from dag wallet menu
2. Click on 'remove a device'

Result: 
After clicking on remove a device the delete button is not visible on the screen.

Expected result: 
Delete button should be visible next to paired device name.

Step 1 
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/adc8112e-96b5-42dd-8eaf-c878121f5d08)
Step 2
![image.png](https://images.zenhubusercontent.com/59495ad151aa2c305782412f/3537a0b1-0678-400a-b678-04167a6bae4f)

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/41218630-6669f1dc-6d64-11e8-9150-7b3c1b9c9827.png)

**Comment by irinadoros** [comment]
It is possible because this device is connected to multidevice wallet - this is correct
