### ISSUE TITLE
update karma config

### ISSUE THREAD

**Issue by iaptsiauri** [dagcoin/dagcoin#138]
`karma.config.js` file should be updated with files which contain business logic and should be tested in order to reflect a proper test coverage, at the moment it includes only the `app.js`

**Comment by RomanShabanov** [comment]
It shouldn't. At this moment we have tests written for only 2 directives. It would create a mess and show incorrect results including all of **.js** files.

**Comment by fishera123** [comment]
@RomanShabanov what do you mean by that? currently we have 100% coverage, I think that's not correct
