### ISSUE TITLE
Explorer shifting towards bottom

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#147]
With every new unit available the explorer moves the chain down, in order to place the new unit in the middle of the screen.
This works well with the byteball client where every unit is relevant but in our case it should happen only when a Dagcoin unit is generated.
The result is that I see the chain moving towards the bottom of the page when a new byteball (but not dagcoin) unit is generated

**Comment by dkostenevich** [comment]
fixed in https://github.com/dagcoin/dagcoin-explorer/pull/5
