### ISSUE TITLE
Can not launch application from first time

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#149]
Already have light wallet with user created on my computer
1. Delete user info (I clear local storage an delete dagcoin-tn folder)
2. Run application 
3. After Terms and Conditions page appears click agree button
4. Choose light wallet and click  continue

Error message appears
From the second time everything start to work

**Comment by vkolt** [comment]
[Uploading Screen Shot 2017-08-01 at 18.26.38.png...]

**Comment by vkolt** [comment]
![Screen Shot 2017-08-01 at 18.26.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6454f26b7191a379e70c2957415c46be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec859f04be34d52a3103763f43b.png)

**Comment by dkostenevich** [comment]
fixed in issue-143 branch #150

**Comment by vkolt** [comment]
still have this problem

**Comment by dkostenevich** [comment]
Problem reproduced after merge with testnet brunch. 
Currently i'm fixed this problem. 
Brunch Issue-143 #150
