### ISSUE TITLE
launching windows client

### ISSUE THREAD

**Issue by dannybreal** [dagcoin/dagcoin#151]
no dagcoin prefix

**Comment by dannybreal** [comment]
![error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59560c70b314ac001a6d4016/125516c66e82c728ace21e0d46ed86882c90c1e5cdf9ad4cae58f3806b1c65267050fa7c20d6e22de71422580b5f4eae470b0b4df9f8dd39baa47e21d40854b088270a36d43703afb9881eba01bb278d4987bebe894ec0fa70.png)

**Comment by yaryribero** [comment]
An user reported the following:

Unable to use Dagcoin 1.1.0
windows 64-bit
"no dagcoin prefix"

The user installed the new version of the client on top of the old one. We changed a lot of strings from byteball to dagcoin: this could be a starting point for the investigation.
We have to provide a way to recover the database.

The error can be seen in the screen.

**Comment by fishera123** [comment]
fixed
