### ISSUE TITLE
New transactions are not displayed on explorer

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#152]
Send a transaction and check unit on explorer. Explorer says that unit not found

**Comment by yaryribero** [comment]
The problem is that the explorer is fetching transactions from the livenet
How to fix:
After 'npm install', Travis should execute the './testnetify.sh' script and only then start the application

**Comment by iaptsiauri** [comment]
This one is fixed, and the PR is open in dagcoin-explorer [https://github.com/dagcoin/dagcoin-explorer/pull/4](url)
