### ISSUE TITLE
Fee Solution: Introduction to the end-user

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#156]
If an end-user has dagcoins but no bytes, a clear and simple pop-up should appear explaining the situation: it's not possible yet to exchange Dagcoins until the user has chosen a way for paying the fees.

A link to more complex documentation should be present on the pop-up with a caption similar to 'learn more ...'

A page hosted on the dagcoin.org site should contain the detailed information about this system.

The end-user should be presented with two choices: 'Buy bytes' and 'Subscribe to a funding hub'.

After choosing a soft alert should linger until the funding method is ready, depending on the funding method chosen:
 'No bytes available ' until confirmed bytes
   OR
 'No funding hub available' until a shared address is issued.

Whenever an user has bytes, this should be the default funding method.

A control in the settings should be available for switching from a method to another.

**Comment by yaryribero** [comment]
Seems another branch of the huge fee solution one.

Rebase onto testnet, thank you :)

**Comment by vkolt** [comment]
Run wallet with a new user. Click "Choose a way of paying fee".  Choose "Subscribe for funding node."  This action redirects back to first pop-up.

**Comment by vkolt** [comment]
rebase is not done

**Comment by vkolt** [comment]
Now pop-up dont appear at all. Choosing funding node as option for paying fee is not possible
