### ISSUE TITLE
Can not remove paired device

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#165]
1. Paire devices 
2. Create shared wallet
3. Remove shared wallet from both devices
4. Try to remove paired device

Trash icon does not appears, so there is no possibility to remove device

**Comment by ilagin** [comment]
Hi Guys, It looks like this functionality is not present in byteball as well. We can try to implement that but it might require a lot of efforts. We need to decide whether it is worth doing that or not
