### ISSUE TITLE
Can not run full wallet

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#166]
Before running wallet dagcoin-tn is removed to clear all user information 

Run application and choose full wallet

Error message appears

**Comment by vkolt** [comment]
![Screen Shot 2017-08-13 at 14.23.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f06b7191a379eb0c2952415a46be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85af049e24a57a7113765f43b.png)

**Comment by dkostenevich** [comment]
can be tested in 'issue-166' brunch #167
