### ISSUE TITLE
[Mac OS] Handle result is not a function

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#170]
![Screen Shot 2017-08-14 at 07.33.48.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594a694905065b001bfb7c75/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f76b7191a378e80c2852415b46be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85afe4be14852a0123e61f43b.png)

**Comment by vkolt** [comment]
how to reproduce?
