### ISSUE TITLE
Running application gives an error

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#180]
Made pull, build application and run.
Error message appears. Then I removed dagcoin-tn folder to run from beginning and issue  was solved. Happened only once for me

**Comment by vkolt** [comment]
![Screen Shot 2017-08-19 at 12.42.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455fa6b7191a379ed0c2f53415d4fbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed593da59b41c95df648e04e5da4153564e07f2431.png)

**Comment by dkostenevich** [comment]
already fixed in #171 PR. ('funding-node-service' brunch).
