### ISSUE TITLE
Create a testnet DAGCOIN + bytes faucet

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#19]
Seen as a black box, this product should be an application running with node.

    It listens on a given ephemeral port (e.g.: 9000)
    The server run on our testnet server.
    It provides an extremely simple web API: URL + address = the service will transfer a certain amount of testnet bytes and dagcoin to such address.
    Amounts: 5000 byes and 5 DAGs
    Every day it will query the byteball testnet faucet in order to refill its own stocks.
    See byteball.org/testnet .
    The scheduling of the task doesn't need to be implemented programmatically: we can use the OS scheduling functionalities (i.e. cronjob in Linux)

**Comment by yaryribero** [comment]
Seen as a black box, this product should be an application running with node.
1. It listens on a given ephemeral port (e.g.: 9000)
The server run on our testnet server.
2. It provides an extremely simple web API: URL + address = the service will transfer a certain amount of testnet bytes and dagcoin to such address.
Amounts: 5000 byes and 5 DAGs
3. Every day it will query the byteball testnet faucet in order to refill its own stocks.
See byteball.org/testnet .
The scheduling of the task doesn't need to be implemented programmatically: we can use the OS scheduling functionalities (i.e. cronjob in Linux)

**Comment by VikaMarkowa** [comment]
Which URL should I use to test it
