### ISSUE TITLE
Structure of the sentences

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#194]
no-bytes.html & pending-modal.html have questionable sentences' structure.

**Comment by RomanShabanov** [comment]
Suggestions:

**no-bytes.html**
1) It's not possible yet to exchange Dagcoins until you not choose a way of paying fees. -> It's not possible to exchange Dagcoins until fees payment type is chosen.
2) Choose way of paying fee  -> Select payment type

**pending-modal.html**
1) Sucessfully changed -> Successfully changed

**Comment by dkostenevich** [comment]
Can be tested in 'Issue-194' brunch #198
