### ISSUE TITLE
dagcoin hub should fire new version event

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#196]
In task #183 we are listening to the even 'new_version_dagcoin', so we need to fire this event somehow when we are releasing new version

**Comment by vkolt** [comment]
Problem with launch new wallet

**Comment by vkolt** [comment]
[Uploading Screen Shot 2017-09-04 at 19.04.43.png...]

**Comment by vkolt** [comment]
![Screen Shot 2017-09-12 at 20.19.24.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6455f16b7191a37aef0c2a58415d4abe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec85df448e94c5ca4153366f43b.png)

**Comment by vkolt** [comment]
Functionality is working only for new wallets, pop-up is not appears for existing users

**Comment by Panyavong** [comment]
Hi Why I can't sent byte from Dagcoin wallet Ver 1.1.0 beta to new version ? 
- I tested many time ago 
Note:  I have received byte from outside wallet But I don't sent to other wallet

**Comment by fishera123** [comment]
Hi, with dagcoin wallet you can only send dags. Unfortunately you cannot send bytes from there

**Comment by fishera123** [comment]
@Panyavong so as I understand you want to take all bytes from dagcoin wallet right ?

**Comment by fishera123** [comment]
@Panyavong I can give you my skype and we can continue privately and I can help you out with this situation.
