### ISSUE TITLE
Activate explorer domains

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#2]
We need to activate the following domains:

testnetexplorer.dagcoin.org -> 194.204.60.69:4000
explorer.dagcoin.org --> 188.166.76.39:4000

**Comment by yaryribero** [comment]
On the way.
There is still a small configuration issue: the domain redirects to the IP address instead of resolving to it

**Comment by yaryribero** [comment]
Livenet seems to work

**Comment by yaryribero** [comment]
Also testnet now: http://testnetexplorer.dagcoin.org/

**Comment by yaryribero** [comment]
How to test. Check the following addresses:

http://testnetexplorer.dagcoin.org/
http://explorer.dagcoin.org/

**Comment by yaryribero** [comment]
Waiting for acceptance from Asse
