### ISSUE TITLE
All BLUE in UI  has to change

### ISSUE THREAD

**Issue by dannybreal** [dagcoin/dagcoin#202]
[Uploading blu.jpg...]

**Comment by fishera123** [comment]
what do you mean by that?

**Comment by vkolt** [comment]
![Screenshot (14).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca4dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3d27e08d874d361e020ac4.png)

**Comment by vkolt** [comment]
![Screenshot (16).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca6dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3d27e08c8f463e19040ac4.png)

**Comment by vkolt** [comment]
![Screenshot (17).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca7dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3d27e08c8d4e3a17000ac4.png)

**Comment by vkolt** [comment]
![Screenshot (18).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca8dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3d27e08c8c4b3918050ac4.png)

**Comment by vkolt** [comment]
![Screenshot (19).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ca9dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84b1b68b49c0ec3d27e08c8a4e3a1b020ac4.png)

**Comment by vkolt** [comment]
![Screenshot (20).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0fa0dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84bfb68b49c0ec3d27e08c89493919040ac4.png)
