### ISSUE TITLE
Sender name is not displayed

### ISSUE THREAD

**Issue by VikaMarkowa** [dagcoin/dagcoin#22]
Receive money without sender address

**Comment by VikaMarkowa** [comment]
[Uploading Screen Shot 2017-06-23 at 13.22.56.png...]

**Comment by fishera123** [comment]
Is sender available in transaction detais?

**Comment by VikaMarkowa** [comment]
![Screen Shot 2017-06-23 at 14.29.47.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594bd850ce45e0002021a000/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f06b7191a379eb0c2958415b49be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e37aa984fc150f44ae64953a71b3f6bf43b.png)

**Comment by fishera123** [comment]
will fix it later

**Comment by deaoja** [comment]
it most likely requires fix in Byteball side, we can start initiating the fix to be done, but it is mostly out of our control from there on.

**Comment by deaoja** [comment]
As a quick fix for release 1.3.3 we decided to simply display text when FROM is empty. Will create separate issue and will link to this.

**Comment by irinadoros** [comment]
Sender address is visible on Home page and in Transaction detail - OK
