### ISSUE TITLE
Android: Scroll missing in receive page

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#223]
On some android screens Receive page doesn't fit and do not have possibility to scroll

**Comment by vkolt** [comment]
[Uploading IMG_4610.jpg...]

**Comment by vkolt** [comment]
![IMG_4610.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d5f8dfabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901db90bbb258b4c8db4b88c44c2e13827f5c6.jpg)

**Comment by fishera123** [comment]
depends #137
