### ISSUE TITLE
Android: header problems in send page

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#226]
1. "Send Dagcoins" text inside header
2. When keyboard is open header became transparent

**Comment by vkolt** [comment]
![IMG_4613.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d5f8dcabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4c8db4ba8a4dc3eb3d22f5c6.jpg)

**Comment by vkolt** [comment]
![IMG_4612.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d5f8ddabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4c8db4ba8a4fc0ef352df5c6.jpg)

**Comment by fishera123** [comment]
depends on #137

**Comment by fishera123** [comment]
we wont have this problem in new ui
