### ISSUE TITLE
Android: Chat recording settings doesn't fit window

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#227]

**Comment by vkolt** [comment]
![IMG_4614.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d5f8dbabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901cbe0bbb258b4c8db5bc8b44c5eb3b25f5c6.jpg)

**Comment by fishera123** [comment]
depends on #137

**Comment by fishera123** [comment]
the same issue happens in other packages 
![screen shot 2017-09-06 at 5 07 23 pm](https://user-images.githubusercontent.com/9304560/30116341-f2aab7cc-9325-11e7-91a0-cbf2a9cd5090.png)
