### ISSUE TITLE
Loosing all bytes at the first transaction

### ISSUE THREAD

**Issue by VikaMarkowa** [dagcoin/dagcoin#23]
Steps to reproduce:
1.Clean local storage 
2. Send bytes(more than needed for one transaction) an dagcoins for new address
3. Send some coins
4. Check bytes balance

Actual result: balance is 0 (bytes come back after next bytes transaction)
Expected result: balance should be correct. Minus fee amount

**Comment by fishera123** [comment]
clean localstorage is not available any more in livenet

**Comment by VikaMarkowa** [comment]
I guess this can happen at the first transaction after  installation

**Comment by fishera123** [comment]
just make so that user still the bytes amount even if it is pending
