### ISSUE TITLE
Sending Wallet address bug.

### ISSUE THREAD

**Issue by JERZAL** [dagcoin/dagcoin#248]
After sending a dagcoin wallet address to Messenger, it shows Byteball instead of Dagcoin. Like this, byteball:B4HBBG3N2ZLYXRVDDMBT5LOSDTLN6FNW

**Comment by fishera123** [comment]
hello, dagcoin is based on byteball  so for now, address should be indexed with byteball, otherwise, address cannot receive bytes.
