### ISSUE TITLE
Enable light wallets to restore from seed

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#288]
Have the light vendor scan for addresses given an extended public key (BIP44).

Since this is a resource intensive operation, be careful not to create a DoS vector.

**Comment by fishera123** [comment]
Current behaviour:
Right now, we allow restoring from seed only for full wallets, because it requires full node.  
 
 
Expected behaviour:
Majority of our users will never use full wallet so we should enable restoring from seed for light wallets also.

**Comment by deaoja** [comment]
DONE CRITERIA:
- if you have light wallet then user should see the option to restore from seed in the global settings
- it should be possible to restore light wallet from seed
