### ISSUE TITLE
Fix full backups restore for >4GB files with unzip library patch

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#293]
The current unzip library does not support certain zip file formats (zip64 data descriptors) for >4GB files. This prevents full backups on full wallets from being restored successfully. The wallet errors: "incorrect password or file" after mostly unzipping the decrypted backup.

## Acceptance criteria
* Add a check for file system (windows) if fat 32 do not allow full wallet creation

**Comment by irinadoros** [comment]
Can't test it with fat 32.
Backup works with file system NTFS - OK
