### ISSUE TITLE
implement push notification

### ISSUE THREAD

**Issue by iaptsiauri** [dagcoin/dagcoin#296]
Currently push notifications are disabled in the wallet. There are four options to implement this.  
1. https://github.com/fechanique/cordova-plugin-fcm
2. https://github.com/arnesson/cordova-plugin-firebase
3. https://github.com/phonegap/phonegap-plugin-push
4. Using OneSignal service
At the moment all four options throw exceptions which are related to the usage of `barcodescaner` plugin

**Comment by msinansahin** [comment]
Changes

andorid-26
Cordova: 7.1.0

**Comment by irinadoros** [comment]
* Push notification come every ~1min 17 sec -> user open it -> there is nothing, just open the app on the page where he lately was - NOK
* When user havs real message and push notification appear, then user can open it, but there is opened Home tab, but should open chat with messages - NOK

**Comment by msinansahin** [comment]
@irinadoros                        
When user clicks push notification or when a push notification comes as application is active, The Chat Tab is made as active tab in application.

Push notification Coming in every n time unit can not reproduced. It is better to test this issue again
 after branch is installed into phone.

**Comment by irinadoros** [comment]
* If application not started at phone, clicking real push notification starts up the application and switches to chat tab - OK
* I still have empty push notifications from hub - NOK

**Comment by msinansahin** [comment]
notification.log file was added to dagcoin-hub  application. For now peer sent new message log is commented.

**Comment by fishera123** [comment]
apply this changes in refactor

**Comment by irinadoros** [comment]
Push notification works when one device send message to another device - OK
Doesn't work for transaction conformation - OK
