### ISSUE TITLE
Backup and Restore

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#3]
We need to implement a Backup and Restore functionality as it is already in place in the byteball client.

This functionality requires a full database available.

Upon installation, the client should ask the end-user to store the master key in a safe place

Given a client with a wallet, an end-user should be able to back it up with the previously saved master key. According to the byteball creator this is not possible without downloading the entire database. This is acceptable for us.

Given:

a complete wallet (not lightweight)
the database downloaded on the machine
a clean installation of the client
An user should be able to provide a master key and have his/her wallet restored

**Comment by VikaMarkowa** [comment]
Seems that I can not choose full wallet. Even if I choose it from menu, it open small expense wallet

**Comment by VikaMarkowa** [comment]
There is no verification for password being the same.  While doing full backup user must set password and repeat it. I entered two different passwords but didn't see any error messages
