### ISSUE TITLE
bring back chat tab

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#300]
Current behaviour:
Right now paired devices/chatbots are located in the side menu.   
 
Expected behaviour:
Paired devices should be under chat tab as well

**Comment by fishera123** [comment]
if the user receives some message notification should appear in chat tab like it is on facebook.

**Comment by vkolt** [comment]
Paired devices are located in the side menu still

**Comment by fishera123** [comment]
It should be on both menus

**Comment by vkolt** [comment]
If I'm on home page and receive message, chat page opens automatically to me. Is it correct behaviour?

**Comment by fishera123** [comment]
I have removed that behaviour and added small badge to the chat menu, so from now when you receive message small badge will appear on chat item
