### ISSUE TITLE
enable possibility to send all amount 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#311]
add button or link(Send all). by clicking on it all amount should be added in amount input in send page. 

Expected behaviour:
* send page should have "send all" button
* clicking on it should  send all amount that he/she holds minus transaction fee.

**Comment by vkolt** [comment]
not possible to clear field filled such way

**Comment by fishera123** [comment]
added notification popup that transaction fee will be automatically excluded from all stable amount user holds
Made amount changeable after send all

**Comment by vkolt** [comment]
Choose "send all" option and clear amount field. Field is marked as validated and send button is available. If field is empty, send button should be deactivated. (currently, clicking button with empty field sends all the money still)
