### ISSUE TITLE
bring back address book

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#312]
we need to have an address book in send page when the user can save addresses and use them later.  

Expected behaviour: 
* in send page user should see address book button
* clicking on button should redirect to address book page
* On address book page user should see "Add new entry" button and the list of the contacts
   * clicking on the contact entry should redirect to send page and insert contact's address in appropriate field
   * clicking on "Add new entry" button should redirect to New entry page
      * On new entry page should be visible two input fields( address and name of the contact)

**Comment by vkolt** [comment]
Name field is limitless. We should limit it.

**Comment by vkolt** [comment]
It is allowed to save entries with the same name. Could  create mess I think

**Comment by vkolt** [comment]
Cursor should show that field with address is clickable (link pointer instead of I )

**Comment by vkolt** [comment]
If qr code is scanned via qr reader then icon of address book covers address
