### ISSUE TITLE
add warning when user tries to change wallet type to full

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#318]
if user will try to change wallet type to full from settings, he/she should see warning and confirm his/her choice. 

content of warning:
The wallet will contain the most current state of the entire Dagcoin database.  This option is better for privacy but will take several gigabytes of storage and the initial sync will take several days.  CPU load will be high during sync

Buttons: Change it, Cancel. If user clicks on change it button wallet type should be changed. In case of cancel, wallet type should be same 

For light wallet, we don't have to show anything.

**Comment by vkolt** [comment]
Add text that coins might be not visible until it will be loaded
