### ISSUE TITLE
settings are broken 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#329]
![screen shot 2017-09-14 at 11 18 00 am](https://user-images.githubusercontent.com/9304560/30419271-741e2960-993e-11e7-9faa-57d7a3c777cb.png)

**Comment by fishera123** [comment]
wallet preferences also

**Comment by vkolt** [comment]
Still broken

**Comment by vkolt** [comment]
![Screen Shot 2017-09-14 at 21.52.45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6455f76b7191a37aee0c2e53415b4bbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec85df24ae94c53a5123463f43b.png)

**Comment by vkolt** [comment]
![Screen Shot 2017-09-15 at 16.40.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6455f66b7191a379e90c2f51415b4ebe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec85df243e24d57a3123363f43b.png)

**Comment by vkolt** [comment]
still small problem
