### ISSUE TITLE
Menu button is blinking a bit while clicking back button

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#381]
Go to wallet preferences and click back button. Check menu button is blinking. (This also happens from other places where is back button is present)

**Comment by fishera123** [comment]
Current behaviour:
Clicking on back buttons has small gap and settings icon becomes visible
 
Expected behaviour:
Clicking back button shouldn’t have any gap and settings icon shouldn’t be visible.

**Comment by vkolt** [comment]
On which branch this task could be tested?

**Comment by fishera123** [comment]
Blinking is fixed but we still have small gaps
