### ISSUE TITLE
add validations to wallet name

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#394]
current behaviour: 
* wallet name doesn't have any validation

Desired behaviour: 
* wallet name should be validated 
   * on min-max characters, 
   * empty spaces
   * numbers
* user shouldn't be able to create multiple wallets with same name

**Comment by ilagin** [comment]
Could someone please explain why should we have a validation on min-max chars and numbers? what if I simply want my wallets to be called "1" and "2", or "a" and "b" @deaoja  @vkolt

**Comment by deaoja** [comment]
This is what we got from beta-testers:

Preconditions:

Steps to reproduce: 
1 - Create or login to dagwallet
2 - Navigate to settings
3 - Click Device name
4 - Delete existing device name and type spaces as new name
5 - Click Save

Result:
New device name will be spaces.

Expected result:
Validation to stop name starting with (consisting only of) space.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

Let me know if this helps or more info is needed. True, one should be able to name their wallet as "a" or "1", but not as a space for an example.

**Comment by vkolt** [comment]
Still able to create wallets with the same name

**Comment by vkolt** [comment]
Name of ticket saying  about wallet name, but in comments mentioned device name. So what exactly this task should change?  What is limitation for characters ?

**Comment by vkolt** [comment]
1. Name still can be the same for two wallets if during editing type already existing name
2. What the min max characters??
3. Device name still can consist with spaces only (not clear from this task if device name in scope)

**Comment by ilagin** [comment]
1. Fixed
2. 50 chars for wallet name and device name
3. Fixed

PR is updated. Moving item to Review
