### ISSUE TITLE
add option for receive page to be visible after user sets the password o the wallet

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#396]
Reveal a Receive page when the user swipes left on the password screen. 

## Current behaviour:
* user sets the password
* wallet requires password on every login

![screenshot_20180323-151935](https://user-images.githubusercontent.com/35455231/37832872-902786d8-2eb2-11e8-93f2-7c7d15e137dd.jpg)

![loginwithpassword](https://user-images.githubusercontent.com/35455231/37833160-4b0c6838-2eb3-11e8-8164-9e92f052f08c.png)

## Desired behavior:
* User can see receive page without inserting any credentials
* Login modal window with pwd will consider with keyboard (on mobile) 

## Possible solution
* Add a field in settings page "Swipe to receive" which will be on/off similar to set password option.
* user turns on receive page swiping, he/she should see swipe left button on password screen
* user swipes left, he/she should get access to receive page 
* user can choose what wallet address is needed

**Comment by rasmusliiva** [comment]
![dagcoin_swipe2](https://user-images.githubusercontent.com/37702190/38034882-d9717edc-32ab-11e8-8cca-e1b6ed64e6b2.jpg)

**Comment by irinadoros** [comment]
* On PC instead of swipe is click

**Comment by irinadoros** [comment]
* User can change wallets from menu without pwd inserting - OK
* User should insert pdw, if he choose some another bottom menu - OK
* If user don't want to insert pwd, he can come back to Recieve page with clicking "Click to receive" - OK
