### ISSUE TITLE
add transaction list and details in home page

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#397]
We need to get rid of history page for once and for all. Split homepage into two parts. the first part will have a slider of wallets. and the second part will have transaction list and transaction detail.

**Comment by vkolt** [comment]
Currently: hand cursor is for not clickable title and arrow cursor is for clickable transaction
Expected: vise versa, hand should appear on hover to clickable transaction

**Comment by vkolt** [comment]
I sent 0.0045 Dag, but on history it is visible as 0
![Screen Shot 2017-12-19 at 20.05.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a37aef0c2b54415f4abe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95bf14be94f53a61a3667f43b.png)

![Screen Shot 2017-12-19 at 20.04.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a37aef0c2b55415a4cbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95bf14be94f52a314356bf43b.png)

**Comment by vkolt** [comment]
After transaction is sent, user redirected to previous transaction details instead of current one

**Comment by fishera123** [comment]
yes I also have this bug

**Comment by fishera123** [comment]
![Screen Shot 2017-12-19 at 9.15.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5949701308f380001b5953db/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a371f1132e4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee4d5645874c56c44a4be8b16eb01ba228d1cd1bfb98b18d2f42f67b6d5db1063474f4dcbed5727a19141c95df748e64c55ad153467e6712431.png)

**Comment by fishera123** [comment]
![Screen Shot 2017-12-19 at 9.16.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5949701308f380001b5953db/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a371f1132d4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee4d5645874c56c44a4be8b16eb01ba228d1cd1bfb98b18d2f42f67b6d5db1063474f4dcbed5727a19141c95df748e64c54a4133064e0742431.png)

**Comment by vkolt** [comment]
Scroll transaction list is not working

**Comment by vkolt** [comment]
Amount is spent today is not correct 

![Screen Shot 2017-12-26 at 20.48.50.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f56b7191a37aef0c2f59415a4ebe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95cf54ae54c50a3123667f43b.png)

**Comment by vkolt** [comment]
In case of multi wallet only one can be exported to csv
