### ISSUE TITLE
See error message while send transaction

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#401]
Wallet doesn't have bytes and subscribed to funding node

**Comment by vkolt** [comment]
![IMG_4728.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d4fbd7abf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb60bbb258b4986b0bb894dc5ec3d22f5c6.jpg)

**Comment by vkolt** [comment]
This error happens after running application straight after previous error
 ![IMG_4729.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d4fbd6abf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4986b0bb8e4bc5eb3b26f5c6.jpg)

**Comment by deaoja** [comment]
please confirm this is reproducible and give info how (multiple wallets in one device? or what are the conditions exactly?)
if it is a corner case then the priority is a bit lower, this is why I ask

**Comment by vkolt** [comment]
Reproducible on second wallet of device. After error appears application crashes. Running it again give second error (second attachment ).  And only running it from second time can make it alive again.

**Comment by fishera123** [comment]
![screen shot 2017-09-27 at 11 03 44 am](https://user-images.githubusercontent.com/9304560/30902474-17668b50-a374-11e7-9a8f-b0475bc23620.png)

I think this is the reason why we are getting this error. My assumption is that either shared address is in the queue for getting funds or either hub just missed them.
