### ISSUE TITLE
Provide better error message on sending

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#402]

**Comment by deaoja** [comment]
Please provide a better error message as this is not helpful. What should the user do in this case? (the case is probably that the funding node is out of bytes) Perhaps: "Could not send payment: funding node is out of bytes - please contact Dagcoin team"

![2017-09-26 10.13.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe903f50dbec57a0875256b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc6e23c20e78d8b4e3e17071a8cfa5527ed.png)

**Comment by deaoja** [comment]
There are 3 conditions that could be failing, please show one or more in case any are actual:
Could not send payment: Funding node is down
Could not send payment: Not enough fuel
Could not send payment: Not enough Dagcoins

So the first is when funding node is not up and running
Second is for when shared address does not have enough stable bytes (they are not confirmed)
Third is when user does not have enough stable Dagcoins in the wallet (they are not confirmed)

**Comment by deaoja** [comment]
Discussed with Lasha and here is the final conclusion:

1) when you click send button (when shared address has bytes that are not stable yet)
IS: Please wait! Funding hub is fueling your wallet, it may take several minutes.
NEW: Please wait! Funding hub is fuelling your wallet. It may take several minutes, please try again a bit later.

2) when you open wallet and funding node is still preparing your shared address and shared address financing
Not able to make transactions until funding hub has fuelled your wallet. It may take several minutes, please try again a bit later.

**Comment by vkolt** [comment]
Second point from previous comment: this message appears every minute or faster. Even if I clicked ok. Annoys a bit

**Comment by vkolt** [comment]
Funding hub is down message is not correct

**Comment by deaoja** [comment]
created a new more precise issue for this - #441
