### ISSUE TITLE
Not clear messages if user sends transaction and pay fee with dags

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#405]

**Comment by vkolt** [comment]
In this case user should not approve anything.
![IMG_4735.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d4fadaabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4981b3be8945c6e03b22f5c6.jpg)

**Comment by vkolt** [comment]
In this case transaction is not under way, I just click twice quickly
![IMG_4737.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6d4fad8abf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb80bbb258b4981b3be8e48c6ea3d21f5c6.jpg)

**Comment by deaoja** [comment]
'This payment is already on the way' - just remove double clicking. So once send has been pressed the send button becomes inactive and displays "sending in progress". If there is error then error is displayed and send button is activated again.

**Comment by deaoja** [comment]
'Transaction created...' (the first screen) the solution is:

First background - this message is shown when user has same wallet on multiple devices, then to send money they also need to approve the transaction on the other device/devices.

So the logic should be changed:
1) Once transaction has been done, I have just pressed SEND button only when the wallet is on multiple devices (if using hub or not), the message should be: 
Transaction created. Please approve it on the other devices.
2) If the wallet is not on multiple devices and only hub needs to approve then user does not have to do anything and this message should be shown:
Transaction created successfully.

**Comment by vkolt** [comment]
Second message is not appear anymore. First is not changed yet
