### ISSUE TITLE
setting for fee payment is disappearing

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#406]
- in my wallet I have bytes
- in the settings I have chosen to use own bytes (choose how to pay fee)
- I make a transaction with my own bytes and all is well
- in the settings I then see only one setting: subscribe to a funding hub and it is not active (screen attached)
- I make a second transaction and it goes through using my own bytes

so all is correct with transactions, it is just confusing that I don't see the active setting anymore that I'm using my own bytes to make a transaction

**Comment by deaoja** [comment]
![2017-09-27 09.53.17.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f404bec17a0876246b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e78d8b46381f021e8af65f27ed.jpg)

**Comment by deaoja** [comment]
Android 8:
- installed a new wallet
- there is no setting at all 'choose how to pay fee' (see the screen below)
- dags are loaded, but they are pending... perhaps that is why? but would make more sense if the selection is still shown as the pending dags will become active any minute

![2017-09-27 10.51.06.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f50dbec1780877256b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e78d8b463616051e8cf75f27ed.jpg)

**Comment by vkolt** [comment]
on switching wallet with bytes to without bytes this choice is also not visible but actually chosen

**Comment by fishera123** [comment]
the reason why it is happening is that fee type option is applied globally. If we want it to be wallet specific we should move fee type option into wallet configuration

**Comment by deaoja** [comment]
#439 will eliminate the need for this issue, closing
