### ISSUE TITLE
Dagcoins are frozen if user is subscribs for funding node

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#407]
1. Make transaction with bytes
2. Wait until transaction is confirmed so dagcoins are available again
3. On settings subscribe to funding node
4. Make transaction again  

As result error message is shown "Can not send payment: Not enough Dagcoins " but actually there is available dagcoins

**Comment by deaoja** [comment]
I was able to reproduce this same message with clean wallet install on Android8:
- installed a fresh wallet
- loaded Dagcoins on it
- Dagcoins became stable
- tried to make first transaction and received this error:

![2017-09-27 10.54.53.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f50dbec17d0872206b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984ec1e23c20e78d8b46371d071c8bf75b27ed.jpg)

Just in case the advanced settings addresses screenshot as well:

![2017-09-27 10.55.28.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f50dbec17c08752b6b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc9e23c20e78d8b46371d031a8cf95d27ed.jpg)
