### ISSUE TITLE
Making transaction acts weird

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#411]
I have 5 dagcoins so I make a transaction.

1) I get popup message to approve it on other devices, but I don't have other devices?

![2017-09-27 19.57.01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f504bec17e0877226b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e78d8a4c3f19061b8efd5c27ed.jpg)

2) then a weird message appears from Funding hub and fueling - why? The transaction was successful as far as I understood from last message?

![2017-09-27 19.57.08.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f504bec17e08772b6b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e78d8a4c3f1605108bfe5f27ed.jpg)

3) transaction seemed to go through, but now my balance is in pending state again? why?

![2017-09-27 19.58.49.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe803f504bec17108732a6b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e78d8a4c3f16001d80ff5a27ed.jpg)

(I  don't know how to rotate the photos :) here )

**Comment by vkolt** [comment]
Duplicated
