### ISSUE TITLE
Fueling takes more than an hour

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#413]
there has to be something else wrong as this fueling is taking already more than an hour.

**Comment by deaoja** [comment]
this was just a loading sign. restarting app helped!

**Comment by vkolt** [comment]
still stack sometimes, works after restart

**Comment by deaoja** [comment]
what is the status right now? can it be closed or what shall we do?

**Comment by vkolt** [comment]
Wanted to test it in android, as it was found there
