### ISSUE TITLE
Catch up with byteballcore

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#419]
Current behaviour:
Using a byteball core commit made on September, 17th 2017 because the newest version introduced a parameter the createWallet method inside wallet_defined_by_keys that causes a null pointer exception with our code.
 
Expected behaviour:
pass the additional parameter (isSingleAddress and start using the latest master branch of the core.

**Comment by vkolt** [comment]
Can not run wallet created from scratch
![Screen Shot 2017-10-17 at 18.51.07.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f46b7191a379e70c2e50415f49be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec850f44ee74c51a11b3365f43b.png)

**Comment by vkolt** [comment]
Money disappears from wallet if it has more than one wallet. Money sent to random address together with transaction

**Comment by yaryribero** [comment]
@Vika: in your project you have a directory name
node_modules/byteball-core
You have to delete it (but not the rest of the content of node_modules) and then run:
npm install
Then
make prepare-dev-tn

After this you will be using the correct byteball-core revision

@ilagin: please correct me if these instructions are not valid on Windows.

**Comment by vkolt** [comment]
I did it, but error still appears
