### ISSUE TITLE
Transaction fee option should be red

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#423]
Description:
Users can choose transaction fee option in global preferences
 
Current behaviour:
Transaction fee option is taking OS default colour. For windows, it is grey for mac it is blue.
 
Expected behaviour:
Transaction fee option should be red in every environment.

![image uploaded from ios 1](https://user-images.githubusercontent.com/9304560/31250578-e2a7a8ac-aa23-11e7-8825-9f8d7aeb8460.jpg)

**Comment by deaoja** [comment]
this issue will be eliminated once #439 is implemented
