### ISSUE TITLE
Send dagcoins amount error (“Not valid”) does not disappear when clearing field

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#424]
Description:
* User opens send page
*  User enters amount
*  User clears amount field.

Current behavior:
Send dagcoins amount error (“Not valid”) does not disappear when clearing field
 
Expected behavior:
Send dagcoins amount error (“Not valid”) should disappear when clearing field.

**Comment by deaoja** [comment]
related to epic #398, should be solved with this epic

**Comment by vkolt** [comment]
Which branch?
