### ISSUE TITLE
navigation bug

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#425]
When adding co-signer in mutlidevice wallet and clicking [ Add new co-signer device ], user is redirected to Add Device menu, clicking back arrow button re-directs user to Paired Devices menu and not Multidevice wallet menu

**Comment by fishera123** [comment]
Description:
 
*    User tries to add co-signer in multidevice wallet
*     User clicks “Add new co-signer device”
*     User is redirected to Add Device menu
*     User clicks “back” button.
Current behavior:
Clicking back arrow button re-directs user to Paired Devices menu
 
Expected behavior:
clicking back arrow button should re-direct user to Multidevice wallet menu

**Comment by vkolt** [comment]
Same thing happens when user pairs with other device. From multidevice wallet he is redirected to chat while pairing and can not go back to multidevice creation page. Wallet creation should be started from beginning

**Comment by ilagin** [comment]
Vika, what are the steps please?

**Comment by vkolt** [comment]
1. Go to multidevice wallet creation page
2. Click choose co-signer dropdown 
3. Choose add new co-signer
4. Pair device
5. After device is paired click back button

Actual result: user redirected to paired devices page
Expected result: user should be redirected back to multidevice wallet creation page

**Comment by vkolt** [comment]
If something was filled before pairing devices , it should stay filled

**Comment by ilagin** [comment]
Hi Vika, we are not saving intermediate state of forms at the moment. That is not currently possible. When you navigate away from a form it loses it's data. I suggest closing the issue as original bug is fixed

@vkolt 
FYI @fishera123, @yaryribero
