### ISSUE TITLE
transaction fee should not be visible as ordinary transaction is history

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#426]
Current behavior:
Users get confused when they make one transaction and in the history, they get two transactions.
 
Expected behavior:
We should somehow mark "transaction fee" transaction in such way that users understood that it is fee and not a transaction made by them.

**Comment by Reemet** [comment]
![transactionfee](https://user-images.githubusercontent.com/14996247/31268041-42e1bb9a-aa83-11e7-8115-37dd7096d9e4.png)

**Comment by deaoja** [comment]
related to task #397

**Comment by fishera123** [comment]
fee transaction is not visible anymore. it is shown in transaction details as fee
