### ISSUE TITLE
implement translation keys 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#428]
texts are already uploaded in crowdin for translators. we need to map those translated texts with origins in the app.

**Comment by vkolt** [comment]
Not translated words
1. All titles on top (in red line)
2. Home page: Wallet balance (under amount), Incoming transactions (in list of transactions)
3. Recieve page: Instruction to copy address 
4. Send page: send button, address field (grey text inside field)
5. History page: My account - Incoming transaction (on list of transactions under the amount)
6. Settings: 'General' title, light/full wallet, language
7. Warning pop-up while changing wallet type
8. Password validation messages
9. Funding  node messages
10. Warning message while sending all funds
11. Plain/ multidevice wallet (titles)

**Comment by fishera123** [comment]
those strings are already uploaded on crowdin and waiting to be translated.
https://crowdin.com/project/dagcoin
