### ISSUE TITLE
security measures on funding node to prevent abuse

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#432]
Several measures are already in place for preventing abuses. We can do more checks:
- Nobody can take profit from the funding node (sneakily including unwanted output). This feature has already been included and tested but not deeply tested
- Nobody can attack the funding node in a way that it suffer economical damage (blocking amounts of bytes whose economical value is greater than the dagcoin fee spent to do so)

**Comment by yaryribero** [comment]
Several measures are already in place for preventing abuses. I'd like to spend more time to check:
- nobody can register as funding node to our discovery service
- Nobody can take profit from the funding node (sneakily including unwanted output). This feature has already been included and tested but not deeply tested
- Nobody can attack the funding node in a way that it suffer economical damage (blocking amounts of bytes greater whose economical value is greater than the dagcoin fee spent to do so)

**Comment by deaoja** [comment]
DONE CRITERIA is not fully available. It is very technical and happens in the backend, Yary has done testing, but more specific abuse testing is required. Yary will provide tool to do as a separate ticket.
