### ISSUE TITLE
State machine manager

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#435]
A module capable of managing a state machine formed by multiple asynchronous operations.

**Comment by fishera123** [comment]
State machine will help to display funding node state in send page

**Comment by yaryribero** [comment]
![DAG Shared Address State Machine.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594a694905065b001bfb7c75/125516c66e82c728ace21e0d46ccb5bd63b18ba89decbb038559f4862c5534331a10a23f75c5ce29bc4a720f0a4d52be011a001ea9aacd39aca439798e550cedd23c0a7cc03418f8b8821db952ee298e4ed1a4a0980e91b6697abad2c51a7c0c0f0a88f85734a5994cc05afe4fe6495cad16242e.jpg)

**Comment by deaoja** [comment]
DONE CRITERIA: we have a module that is able to manage a finite state machine, it receives some input stimula and according to this moves from one state to subsequent and is able to communicate it to interested parties.
Very technical task :)
