### ISSUE TITLE
Provide correct error message in case of network errors

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#441]
Network down includes when funding node or any hub is not reachable or the node is down
Grew out from issue #402

DONE CRITERIA:
- if weird connection error happens then more meaningful message is shown to user instead of the current one with weird characters and connection word in it

**Comment by vkolt** [comment]
When connection problem is happens I see correct message, but I'm able to click send button second time and then I see wrong message again
![Screen Shot 2017-10-17 at 20.04.31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f46b7191a37aef0c2b55415c4fbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec850f44de14d50a611316af43b.png)

**Comment by vkolt** [comment]
Do not see any messages now. Button becomes grey for a while and then is available again. By clicking it error message appears that transaction is on the way. Tested on Mac

**Comment by fishera123** [comment]
tested on mac. the behaviour seems to be correct. I have clicked twice on send button, message appeared then transaction is on the way and after that it displayed connection error message.

**Comment by fishera123** [comment]
I have changed "This payment is already under way" to "This payment is being processed"
