### ISSUE TITLE
request payment

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#453]
enable functionality to request a specific amount: a link should be visible in receive page, it should redirect you the page when you can specify the amount of dags you want to receive and then generate qr code.

**Comment by ilagin** [comment]
implemented in branch issue-543

**Comment by vkolt** [comment]
1. After payment is made from request, message is send automatically "Payment ... DAG". It is send from sender, but receiver do not see it. 
2. Link on 'after payment' message redirecting on history page of opened wallet. But in case of few wallets it could be another history page. Should redirect to correct history page
3. Decimal amounts  are not allowed for request in sending page (1.5 for ex)
4. Input field does not have limits and qr code is scanned with problems after it is generated for 14 digits

**Comment by vkolt** [comment]
For 1 and 2 separate task is created. 3 and 4 should be fixed in scope of this task

**Comment by ilagin** [comment]
3 and 4 fixed in branch issue-543
