### ISSUE TITLE
Can not run wallet after initial creation

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#457]
Branch: issue-419
Environment: Windows
node_modules was updated

Create wallet from scratch.

**Comment by vkolt** [comment]
![Screenshot (27).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0fa7dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84bfb68b49c0e03f23e18c884d3b1f050ac4.png)

**Comment by fishera123** [comment]
this bug is happening only in issue-491 branch. connected with #491

**Comment by vkolt** [comment]
Still present for me in branch issue-461
