### ISSUE TITLE
Fix client after byteballcore update

### ISSUE THREAD

**Issue by ilagin** [dagcoin/dagcoin#461]

**Comment by vkolt** [comment]
Single address switch design is broken in this branch
![Screen Shot 2017-10-20 at 17.29.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f36b7191a379e80c2958415c4cbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec850f34ae04d5cad133666f43b.png)

**Comment by vkolt** [comment]
Still happens in Mac
