### ISSUE TITLE
Changing wallet type resets wallet name if name is empty string.

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#474]
(from beta testers)

Preconditions:
Steps to reproduce:
1 - Navigate to settings
2 - Set wallet name to empty string
3 - Change wallet type

Result:
Wallet name is resetted to default.

Expected result:
Since empty string is allowed expect wallet name to remain emtpy string.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

**Comment by ilagin** [comment]
Hi Dea, we do not allow neither wallet names nor device name to be an empty string anymore.
@deaoja
