### ISSUE TITLE
After clicking agree to terms checkbox confirm button is unresponsive.

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#475]
(from beta testers)

Preconditions:
First install on device.

Steps to reproduce:
1 - Click accept terms and conditions

Result:
Confirm button is unresponsive for ~1 second.

Expected result:
Confirm button is responsive without delay.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

**Comment by fishera123** [comment]
display loader
