### ISSUE TITLE
Device name length should have a limit.

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#478]
(from beta testers)

Steps to reproduce:
1 - Navigate to Settings
2 - Click Device name
3 - Enter new device name

Result:
There is no limit to the length of device name.

Expected result:
There should be some length for device name.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

**Comment by deaoja** [comment]
![device_name_length.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59ca0047d58e2c0011dc708c/125516c66e82c728ace21e0d46ec918c2a81869681e8b2469b51f59a2e522f316546b3397f8fe62bab0021435a564aa546585c15a9f18f22afe23c70885a58b9d8685e20d42103eee9dc4be05ce36ade0d97bcae884dcae93825ee88894e3b1c011b89fa4f78.png)

**Comment by dimuha** [comment]
Can not reproduce. Most likely was fixed with the other bugs.
