### ISSUE TITLE
Spending Restriction password - Field shows to be clickable but password settings only works when clicking slider.

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#479]
(from beta testers)

Steps to reproduce:
1 - Navigate to Settings
2 - Click Spending Restriction password field name

Result:
Password on/off setting only works when clicking slider.

Expected result:
Password on/off setting works when clicking anywhere on the field Request password.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

**Comment by vkolt** [comment]
Do not see changes
