### ISSUE TITLE
Not mathcing repeat password returns to set password.

### ISSUE THREAD

**Issue by deaoja** [dagcoin/dagcoin#480]
(from beta testers)

Preconditions:
Steps to reproduce:
1 - Navigate to settings
2 - Activate Spending Restrictions password
3 - Enter valid password
4 - Enter not matching repeat password

Result:
User is returned to enter password.

Expected result:
Error message of not matching password is returned and user stays in repet password prompt.

Tested on MacBook Pro (Retina, 13-inch, Early 2015), OS Sierra v10.12.6.

**Comment by fishera123** [comment]
related to #481
