### ISSUE TITLE
Funding node mixing wallets after recovering from seed

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#503]
Preconditions: wallet with main (with coins) and additional wallets (without coins)

Steps:
Recover wallet from seed

Results: not possible to send coins using funding node anymore. Error message says:  "The funding service is currently not supported on secondary wallets. Load some bytes on it". but before recovering from seed wallet with coins was main

**Comment by irinadoros** [comment]
Close it. Will fix with fork.
