### ISSUE TITLE
customer integration

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#504]
discuss with Priit about details

**Comment by yaryribero** [comment]
Workflows

 1. pay the invoice before expiry
    - this is the normal flow
    - payment is made
    - payment API is notified that the payment was successful
  2. cancel the payment (actually press "Cancel" in the app)
    - payment API is notified that the payment was explicitly cancelled
  3. do nothing (close the app etc)
    - payment API is not notified, it eventually understands that the invoice has expired
  4. attempt to pay the invoice after it has expired
    - the APP UI should generally stop the user from paying expired invoice
    - if somehow this still happens and APP reports to API that payment was successful but the invoice has actually expired, the payment API flags it as paid after expiry and the merchant's site can decide what to do with it (it could refund the user or just accept it)

**Comment by yaryribero** [comment]
The API

- return "state": "EXPIRED" if time since invoice was created exceeds X seconds (that's either same for all or invoice parameter), the APP only allows to pay "PENDING" state invoices
- return "validForSeconds": 600 etc to show that the invoice is currently still valid for 600 seconds (10 minutes), this way we don't rely on the device clock to be accurate

**Comment by yaryribero** [comment]
The API is a remote API controlled by Priit

The merchant requests the API to create an invoice for a payment with an expiry date
The QR contains just an invoice ID
The App calls the API for the invoice content:

{
  "id": "FDCEB8A65915B84A1B73A90C0EFACE08",
  "userId": "8361883F107B809FC02E3207BC65B8C5",
  "environmentId": "930CAA2DF97287730EFB7807A7CD7B0F",
  "price": 10,
  "currency": "DAG",
  "description": "Test payment",
  "data": "{\"sessionId\": \"foobar\"}",
  "paymentId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "qrCodeUrl": "/api/invoices/qr/FDCEB8A65915B84A1B73A90C0EFACE08",
  "state": "PENDING",
  "createdDate": "2017-11-14T07:56:32.257Z",
  "updatedDate": "2017-11-14T07:56:32.257Z"
}

**Comment by yaryribero** [comment]
good, so let's agree on the state change call from the APP to API

we need to handle at least two cases right
1. user cancels the payment
2. payment is successful


new messages
[12:42] 
the APP can use the invoice id that it scanned right, and just have hardcoded API endpoints again


[12:45] 
cancelling is probably easy, just call an endpoint like PUT https://example.com/api/invoice/FDCEB8A65915B84A1B73A90C0EFACE08 with payload like
```{
  "state": "CANCELLED"
}```

**Comment by yaryribero** [comment]
The invoice id has to be saved into the dagchain unit
