### ISSUE TITLE
Error appears while creating additional wallet

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#510]
Go to menu and add new plain wallet.
As a result error message appears. Wallet is created

**Comment by vkolt** [comment]
![Image uploaded from iOS.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1999b2487c3bc9fe5b042a058f4d42f54287e690d8c1832c9a138ad4d71040c1b5ca6535d5640f5fe8928f7e3347683555fedd16f5927923414adec9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3f1e071c80fd5d32a49b4eda15.jpg)

**Comment by dagcoin1** [comment]
https://sentry.io/dagcoin/dagcoin/issues/400383251/
