### ISSUE TITLE
ERROR when I cancelled sync of all new units  on macOS Sierra

### ISSUE THREAD

**Issue by siim944** [dagcoin/dagcoin#53]
This error occurs now every time when I open DAGCOIN program on macOS Sierra. It's probably caused because I quit the program when I after I installed it while it was syncing new units. 
After pressing OK it quits.

![screen shot 2017-07-02 at 13 18 01](https://user-images.githubusercontent.com/29834217/27768980-e88c630c-5f28-11e7-8961-5e6e5c0c69d0.png)

**Comment by fishera123** [comment]
@yaryribero I cannot reproduce this bug. Tested on livenet and testnet

**Comment by vkolt** [comment]
Can not reproduce. (Closed app during sync, switch off internet connection during sync)
