### ISSUE TITLE
Single address text doesn't fit its field

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#535]
## Expected Behavior
Text should be completely visible and fit the field

## Current Behavior
Now only part of text is visible 

## Steps to Reproduce (for bugs)

1. Go to wallet preferences (dots next to wallet name)
2. Check single wallet field

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by vkolt** [comment]
![Screenshot (43).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec09a3dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84bfb68b49c1e93c27e48d86493f1c050ac4.png)

**Comment by dimuha** [comment]
It looks like this now:
![Screen Shot 2017-11-21 at 11.14.53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f26b7191a379ee0c2a55415a4dbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f44ee7495dad16326af43b.png)
![Screen Shot 2017-11-21 at 11.14.31.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f26b7191a379ee0c2a55415c4fbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f44ee7495dad163563f43b.png)
