### ISSUE TITLE
Order chat  based on last conversation 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#542]
## Expected Behavior

Chats in paired devices should be ordered  based on last conversation the highest
## Current Behavior

Currently it is ordered by name, so sometimes user can't find conversation unless pair replies and it appears on top with red dot.

**Comment by vkolt** [comment]
This branch has problem with opening add new wallet page
![Screen Shot 2017-11-30 at 20.13.13.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226457f36b7191a37aef0c2a52415e4dbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95af64de4455ca31b366af43b.png)
