### ISSUE TITLE
Addresses in wallet preferences are not visible fully

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#547]
## Expected Behavior
Addresses and its info should be fully visible

## Current Behavior
Only part of addresses is visible 

## Steps to Reproduce (for bugs)

1. Navigate to wallet preference page
2. Choose Advanced
3. Click Wallet Information
4. Scroll to  All wallet addresses and Balance by address

## Your Environment

* Version used: 1.3.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): all
* Link to your project:

![Screenshot (44).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec09a4dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d84beb68b49c1e93f2de3898a4b3d1a0d0ac4.png)

**Comment by dimuha** [comment]
Looks like this now:
![Screen Shot 2017-11-22 at 12.29.55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f16b7191a379ed0c2958415a4bbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f54fe74b50a5103e61f43b.png)
![Screen Shot 2017-11-22 at 12.30.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f16b7191a379ed0c2851415e4fbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec959f54fe74b53a210336af43b.png)
