### ISSUE TITLE
Wallet and device long name break design

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#548]
## Expected Behavior
30 symbols text shouldn't break name field

Wrap text in name fields

## Current Behavior
Up to 30 symbols name doesn't fit name field 

## Steps to Reproduce (for bugs)

1.Go to settings
2. Edit device name using 30 symbols string
And
3.Go to wallet preferences
4.Edit wallet name using 30 symbols string

## Your Environment

* Version used:1.3.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):all
* Link to your project:
![Screenshot (45).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec09a5dd6b0a65633b0ba92e7391a172fd17225556584eaf100d5742f5f0dd2ba6b43a23de550eec857f4366846c4ff8e7df46f554f832815d87b7b68b49c1e93f2dee8e884e38190c0ac4.png)

**Comment by dimuha** [comment]
Looks like:
![Screen Shot 2017-11-24 at 19.23.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f76b7191a379e60c2952415b4dbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f34fe54957ad153561f43b.png)
![Screen Shot 2017-11-24 at 19.27.54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a02ec658ce02900118c8d67/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226456f76b7191a379e60c2956415a4abe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec959f34fe54854ad153466f43b.png)
