### ISSUE TITLE
Ability to read a new type of QR code

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#551]
## Expected Behaviour

1. The application is able to scan a QR with a json structure containing only a payment id.

2. Subsequently it will call a configured API for additional information

3. If some error is returned by the remote payment API, an error message is displayed

4. Finally it will fill the payment form with such information, including a countdown (#552)

**Comment by irinadoros** [comment]
* The application is able to scan a QR with a json structure containing only a payment id. - OK
