### ISSUE TITLE
Payment countdown

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#552]
## Expected Behavior

A timer should appear somewhere in the payment form, if this functionality is requested.

- The timer is a configurable countdown
- When the countdown completes an error message is displayed and the payment can not take place

**Comment by irinadoros** [comment]
* When the countdown completes an error message is displayed and the payment can not take place
-- There is message "Payment request expired", amount and receiver address is empty and [Send] button is not active
