### ISSUE TITLE
Can not recover from seed

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#559]
## Expected Behavior
After recovering from seed coins should be restored

## Current Behavior
Error message appears (see screenshot)

## Steps to Reproduce (for bugs)

1. Navigate to settings and choose backup wallet seed
2. Click Show the wallet seed anyway 
3. Copy words displayed there
4. Install new wallet from scratch
5. Navigate to Settings and choose Restore from seed
6. Paste words there and click recover

## Your Environment

* Version used: 1.3.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Android
* Link to your project:
![IMG_4930.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46c1b9bd1cd6dafadfabf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb80bbb258a4e86bebc8c4bc9e13e24f5c6.JPG)

**Comment by yaryribero** [comment]
I could backup and restore successfully on my android device. Is there any additional context? What version of android was it?

**Comment by vkolt** [comment]
android 7.1.1

**Comment by msinansahin** [comment]
Found another error

public/dagcoin.js:7779 Uncaught TypeError: Cannot read property 'address' of undefineddb.query @ public/dagcoin.js:7779
