### ISSUE TITLE
Export transactions

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#574]
## Expected Behavior

We should enable users to export transactions in desired format (excel, csv etc)

## Your Environment

* Operating System and version (desktop or mobile): ALL

**Comment by vkolt** [comment]
Not clear behaviour: 
1. export history to csv 
2. Delete this file from computer
3. Try to export once more  with the same file name

Actual result: nothing happens, file is not saved, nothing is displayed to inform about error
Expected result: save file with the same name if it previously was deleted or show explanation information

**Comment by vkolt** [comment]
If history is empty buttons shouldn't be shown
![Screen Shot 2017-12-10 at 20.45.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f36b7191a37aef0c2f54415a47be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95aff48e04b54a3103464f43b.png)
