### ISSUE TITLE
Hide balance

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#579]
## Expected Behavior
* The app should give users the possibility to hide balance
* User can't do amount visible accidentally

**Comment by rasmusliiva** [comment]
![dagcoin_balance_hidden_option](https://user-images.githubusercontent.com/37702190/38030349-08aab962-32a1-11e8-932a-c0b2b0ec94bf.jpg)
![dagcoin_balance_hidden](https://user-images.githubusercontent.com/37702190/38030350-08c8dcc6-32a1-11e8-927b-b937edb90aa5.jpg)
![dagcoin_balance_option](https://user-images.githubusercontent.com/37702190/38030351-08e86da2-32a1-11e8-97b1-a70e270cf687.jpg)
![dagcoin_balance](https://user-images.githubusercontent.com/37702190/38030352-090599fe-32a1-11e8-92c4-40f8bfa704a3.jpg)

**Comment by rasmusliiva** [comment]
Icon used:

https://www.flaticon.com/free-icon/blind_716074#term=hide&page=1&position=30

**Comment by irinadoros** [comment]
The icon should be in the center - NOK
Copy and Share possibilities are appear - NOK
branch: task-579-n
![hidebalance](https://user-images.githubusercontent.com/35455231/38494180-93d9630c-3bfd-11e8-874c-706eef423584.jpg)

**Comment by irinadoros** [comment]
On the PC I can't open app - NOK
![image](https://user-images.githubusercontent.com/35455231/38494276-e75c2d16-3bfd-11e8-9695-a2881e9f5f07.png)

**Comment by msinansahin** [comment]
Center position problem in some android phones was fixed.

**Comment by irinadoros** [comment]
Balance should be with one "l"

**Comment by irinadoros** [comment]
Windows 10 in branch task-579-n:
<img width="702" alt="hiddenbalance" src="https://user-images.githubusercontent.com/35455231/38548356-3a723ba0-3cba-11e8-8195-58a1c34bf63d.png">

* Word "balance" is on L - OK
* Transactions amount is hidden also - OK
* On PC works with mouse and with touch on click - OK
