### ISSUE TITLE
Can not open chat anymore if multideviced wallet is created with that particular device

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#589]
## Expected Behavior

Chat should be still usable 

## Current Behavior

If multidevice wallet is created with other device, chat with this device could not be opened and used anymore. 

## Steps to Reproduce (for bugs)

1. Pair a device (check - chat is available to use)
2. Create a multidevice wallet with this device
3. Go to Paired devices page
4. Check that chat is not clickable anymore

## Your Environment

* Version used: 1.3.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): all
* Link to your project:

**Comment by ilagin** [comment]
Hi, this is fixed in scope of #314
