### ISSUE TITLE
explorer should show transaction times

### ISSUE THREAD

**Issue by dannybreal** [dagcoin/dagcoin#59]
when you open the transaction in the right-hand side view it should display the time of the transaction like in the byteball explorer

**Comment by yaryribero** [comment]
Is there a branch or pull request associated to this ticket?

**Comment by fishera123** [comment]
yes, it is in explorer.
https://github.com/dagcoin/dagcoin-explorer/pulls

**Comment by yaryribero** [comment]
Changes deployed on testnetexplorer.dagcoin.org
