### ISSUE TITLE
App crashes if user navigate to Paired devices page while multideviced wallet

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#590]
## Expected Behavior

App shouldn't display error and crash

## Current Behavior

Error message: "Illegal state" appears. App crashes

## Steps to Reproduce (for bugs)

1. Pair devices
2. Go to add new wallet page and choose multideviced wallet
3. Type a name, choose 2 co- signers, choose that device in dropdown and create a wallet
4. New page will appear "waiting fo co-signers"
5. On another device confirmation pop-up should appear. Do not make any action with it
6. In first device, try to navigate from "waiting.." page to Paired devices page"

## Your Environment

* Version used:1.3.4
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):Mac
* Link to your project:
![Screen Shot 2017-12-03 at 20.05.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f06b7191a37aef0c2b54415b4fbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3daa984ec95af549e74a50a3113061f43b.png)

**Comment by vkolt** [comment]
Also I tried to cancel wallet creation and saw another error :
![Screen Shot 2017-12-03 at 20.06.49.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f06b7191a37aef0c2b57415b47be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95af549e74554a4103060f43b.png)

**Comment by ilagin** [comment]
When testing, please note that due to address creation limitations you won't be able to switch between wallets while one of the wallets is "waiting fo co-signers"

@vkolt

**Comment by vkolt** [comment]
Second error is still present if I cancel wallet creation

**Comment by ilagin** [comment]
Hi Vika,  I'm unable to replicate the second issue on win. Is it only happening on a mac? If so, could you please resolve this one and create a separate ticket so that a person with a mac can solve this?
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5968d2ffc79cb0001fb72f0f/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f67224dcb478ec437e59595647f841585d42afad802ea7e22e6c981e5ab38532022d8c6853beb2901eb80bbb258a4c85bfbe8d4ac8ea3c21f5c6.png)

**Comment by vkolt** [comment]
Error occurs  on windows as well. Reproduces  when russian language is chosen

**Comment by fishera123** [comment]
@ilagin maybe somewhere we are using ```gettext``` sometimes this is breaking functionality. If you will find one change it to ```gettextCatalog.getString```
