### ISSUE TITLE
Navigation bar directive

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#591]
Support of *invert* state.
Support of ng-transclude to pass any additional html to the header
Support of *go-back* conditions to display either a burger icon or back arrow depending on value of the property.

**Comment by vkolt** [comment]
After name of wallet is changed, user redirected to first setting page instead of staying on system page

**Comment by RomanShabanov** [comment]
@vkolt Wallet name? Or device name?

**Comment by vkolt** [comment]
device name
