### ISSUE TITLE
Redesign the settings page

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#592]
Apply UI changes to global settings page

**Comment by vkolt** [comment]
Is white background and between name field and button correct?
![Screen Shot 2017-12-19 at 20.47.18.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a37aef0c2f56415e46be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f35aa984ec95bf14be84e57a7143766f43b.png)

**Comment by fishera123** [comment]
![Screen Shot 2017-12-19 at 9.11.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5949701308f380001b5953db/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455fa6b7191a371f1132a4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee4d5645874c56c44a4be8b16eb01ba228d1cd1bfb98b18d2f42f67b6d5db1063474f4dcbed5727a19141c95df748e64c55ac103767e2772431.png)

**Comment by fishera123** [comment]
here is how settings look like on small devices
