### ISSUE TITLE
Intro v2.0

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#593]
Make intro page more "sexy" by applying storytelling mode with sick animation.

## Acceptance criteria
Intro page changes include: 
1) changing design of introduction page(first page user will see) 
2) moving terms and condition to separate page as a link and add two checkbox that briefly says about the responsibilities 

- Add svg animation to intro slider.
- Create intro confirm route.
- Display terms of use inside the modal instead of dedicated view.

**Comment by irinadoros** [comment]
On the terms and condition page, there is no possibility to get back or disagree with terms - NOK

## Expected Behavior
* there is red bar with name "Terms and conditions" and back arrow (<-)
* there is button [Not agree]

**Comment by irinadoros** [comment]
•	Almost done! view animation creates scroll bar on Window 10 - NOK
The animation should be without scroll bar and text should be in one row without jumping
•	"I have read, understood and agree" block rides from the middle of screen/app window - NOK
"I have read, understood and agree" block should ride from the app bottom.
![almostdoneconfirmation](https://user-images.githubusercontent.com/35455231/35434627-8065e97c-0290-11e8-96d2-6ac37ba64c8f.PNG)

**Comment by irinadoros** [comment]
* Terms of use view has a header on a white background - OK
* Terms of use view has a [Back] button as an arrow - OK
* Almost done view has no scroll bar - OK
* When user came back from terms page, there is checked box with agreement and [Confirm & finish] button is active/colored red - OK

**Comment by irinadoros** [comment]
Terms of use view has incorrect scroll bar - NOK
It should be with the same design as in whole app.
<img width="322" alt="initialrunrecomended" src="https://user-images.githubusercontent.com/35455231/35499673-15267534-04dc-11e8-83c8-18df7a34328f.png">

**Comment by irinadoros** [comment]
* Scroll bar is still there...  Windows 10

**Comment by irinadoros** [comment]
Initial run terms are scrollable but user can't see any scrollbar - OK
Settings Terms get windows standard scrollbar, but will fix it in another task.
