### ISSUE TITLE
Dagcoin explorer tests

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#6]
Some tests are required to validate the explorer.

Testnet environment: 194.204.60.69:4000

**Comment by yaryribero** [comment]
User experience tests:
1. Does the application load and reload fast enough?
2. Try to select a node and refresh
3. Drag the graph
4. Click on an old node, reload the page and drag the graph to the bottom: does it load the next nodes?
Functional tests
1. Create a transaction with a client. Do you see it appearing immediately on the explorer?
Load tests
1. We need to simulate multiple users querying and find the limits of the application

**Comment by VikaMarkowa** [comment]
Should definition of new asset look this way?
![Screen Shot 2017-06-26 at 19.27.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594bd850ce45e0002021a000/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256456f56b7191a379e60c2956415a4cbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc150f242e54556a0173e61f43b.png)

**Comment by fishera123** [comment]
Yes this is the definition of the asset

**Comment by VikaMarkowa** [comment]
If I choose a node and refresh a page, should chosen node stays the same. Or it always comes back to last one?

**Comment by dannybreal** [comment]
should display dagcoins instead of bytes in the correct field
