### ISSUE TITLE
Add restore from seed in intro page 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#609]
## Expected Behavior

The user should have the possibility to restore from backup without creating wallet first.
## Current Behavior

Currently, user is only able to restore with backup
## Possible Solution

reuse the view from backup options. related to the #576

**Comment by vkolt** [comment]
Fatal error: Maximum call stack size exceeded

**Comment by vkolt** [comment]
wallet design seems broken in this branch
[Uploading Screen Shot 2018-01-03 at 20.55.44.png...]
