### ISSUE TITLE
Wallet name does not change in wallet information page

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#622]
## Expected Behavior

Wallet name should change in info page

## Current Behavior

Wallet name doesn't change 

## Steps to Reproduce (for bugs)

1.Go to wallet preferences
2.Change wallet name
3.Go to wallet information
4.Check wallet name 

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by fishera123** [comment]
is it on testnet?

**Comment by fishera123** [comment]
it should stay same. You can change wallet allies only not the name itself.
