### ISSUE TITLE
Address book is slow on android

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#625]
## Expected Behavior

If book has some addresses stored, it should be shown immediately when book is opened

## Current Behavior

It may take up to minute to load addresses stored in book

## Steps to Reproduce (for bugs)

1. Go to send page 
2.Scan address 
3.Open address book and store scanned address there
4.Change a page 
5. Go back to send page
6. Open address book

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Android 7.1.1
* Link to your project:

**Comment by RomanShabanov** [comment]
I am working on an address book right now #616
