### ISSUE TITLE
Notifications sidebar

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#644]
- Display and manipulate notifications.
- Introduce notifications settings.

## Possible solutions
* Need remove old notifications that have been read
* Notifications are in local storage

**Comment by irinadoros** [comment]
Local branch, Windows 10
* Delete wallet notification - OK
<img width="634" alt="notification2" src="https://user-images.githubusercontent.com/35455231/39915867-be482df8-5511-11e8-8f0a-b82bc5311676.png">
