### ISSUE TITLE
Transactions Details

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#645]
## Expected Behavior

This task suggests design changes to transaction details model. new design includes changes icons, modal appearance etc.

**Comment by fishera123** [comment]
can you make so that we won't have a scroll in transaction details? Modal itself is big I guess

**Comment by irinadoros** [comment]
Win10, local: 
* transaction details modal is not scrollable - OK
* transaction details modal has icons - OK
* lazy loading and smooth motion - OK

**Comment by irinadoros** [comment]
![transactionsdetailshorisontalscroll](https://user-images.githubusercontent.com/35455231/35334051-aafc3a56-0119-11e8-9954-e07b272f4d8e.png)

**Comment by RomanShabanov** [comment]
Fixes #689

**Comment by irinadoros** [comment]
![home645](https://user-images.githubusercontent.com/35455231/35379103-acc6d072-01bd-11e8-868c-8956297ebcb3.png)

There is horizontal scroll!
