### ISSUE TITLE
Settings inner pages

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#648]
Apply new style to settings inner pages.

**Comment by irinadoros** [comment]
On the address book view doesn't work swiping - NOK

**Comment by irinadoros** [comment]
Chat view has a windows scrollbar - NOK
Contact view has a windows scrollbar - NOK

**Comment by irinadoros** [comment]
* Chat view - OK - don't have scrollbar anymore
* Address book scrollbar is OK
* Menu don't have a scrollbar - OK
* Terms of use has an app scrollbar - OK
* Session log has an app scrollbar - OK

**Comment by irinadoros** [comment]
Send -> open address book -> there is windows scroll:
![image](https://user-images.githubusercontent.com/35455231/35860744-deb86728-0b4d-11e8-8c27-8e5be2de698f.png)

**Comment by vkolt** [comment]
Long name doesn't fit header

![Screen Shot 2018-02-06 at 20.12.00.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/6d174f49-00f5-4310-a808-873e1ca7f349)

**Comment by vkolt** [comment]
Text field doesn't have bottom padding and not visible well. Send button icon has poor image quality.

![Screen Shot 2018-02-06 at 20.12.54.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/faa72460-68fd-42c2-a35b-b52805925b10)

![Screen Shot 2018-02-06 at 20.23.48.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/f6382c44-efef-4745-adb8-e8a680353ba3)

**Comment by irinadoros** [comment]
Addressbook loading from Send tab is slow - NOK. In testnet it was nice.

**Comment by vkolt** [comment]
Code scanner is not working on address book 

![Screen Shot 2018-02-08 at 18.11.18.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/3e9b9447-11c0-42a7-8019-7f806f1818ab)

**Comment by vkolt** [comment]
Design of headers is so different. I think it is better unify it 

![Screen Shot 2018-02-08 at 18.25.40.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/48898dc0-7b82-4dc8-90c5-3b0df3f65dce)
![Screen Shot 2018-02-08 at 18.26.31.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/d0161e48-1ab3-45db-9e84-09641e28a638)
![Screen Shot 2018-02-08 at 18.25.53.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/6495226c-df46-44df-82ec-1db1529f48af)
![Screen Shot 2018-02-08 at 18.26.12.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/e0642093-af3e-4a91-8cfc-3dba6735f6e0)

**Comment by vkolt** [comment]
All fields should be limited in contact creation template. 

![Screen Shot 2018-02-08 at 18.33.42.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/b214b69e-c9dd-4722-b2be-0a0234e55243)

![Screen Shot 2018-02-08 at 18.35.58.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/0fd01399-b7b9-4169-b0d9-1b861dbd748b)

**Comment by irinadoros** [comment]
* Contacts are in alphabetical order - OK
* For example names with russian letters are after latin letters in alphabetical order as well - OK
