### ISSUE TITLE
Sign the Windows app with signtool

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#66]
You can download such tool here:
https://stackoverflow.com/questions/31869552/how-to-install-signtool-exe-for-windows-10

What kind of certificates do you need?

**Comment by yaryribero** [comment]
https://stackoverflow.com/questions/31869552/how-to-install-signtool-exe-for-windows-10

**Comment by yaryribero** [comment]
We have the credentials but we don't know where to use them. Ask Chris

**Comment by ilagin** [comment]
Cannot upload the file bigger than 25 MB. Please find the signed version  in latest releases
