### ISSUE TITLE
End user sees on desktop taskbar DAGcoin icon when app is open

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#663]
## Expected Behavior
End user sees on desktop taskbar DAGcoin icon when app is open

## Current Behavior
When app is open in desktop, on a taskbar I see grey cube icon![AppIconOnTaskbar.PNG](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/584517e1-26d6-4c7e-875d-eaf5d9b84ee6)

*Environment*
* Windows 10

## Acceptance criteria:
* taskbar icon is same as DAGcoin icon
* icon changed on Windows, Linux, Mac

**Comment by msinansahin** [comment]
@irinadoros are you running application via downloading from dagcoin.org, or with the command` nw .`
According to https://github.com/nwjs/nw.js/wiki/Icons#windows says, application icon is created only as packaging.

**Comment by irinadoros** [comment]
There is no problem in LIVE. Taskbar icon and app icon is same on Windows. "Problem" is only on test environments. - OK
