### ISSUE TITLE
Address Book inputs validation

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#664]
## Expected Behavior

Address book address and name input should become mandatory. The address should be checked if it is valid.

**Comment by irinadoros** [comment]
* Wallet address and First name are mandatory - OK
* Wallet address validation valid/not valid - OK
* Notification "Address is already exists", if address book has already had it - OK
* Letters with dots in First/Last- name, description, email - OK
* Sort by first name in alphabetical order - OK

**Comment by irinadoros** [comment]
* Wallet address and First name are mandatory - OK
* Wallet address validation valid/not valid - OK
* Letters with dots in First/Last- name, description, email - OK
* Sort by first name in alphabetical order - **NOK**
* Notification "Address is already exists", if address book has already had it - OK, but there is small bug with [Save] button, if it partly covered - **NOK**

**Comment by irinadoros** [comment]
Lasha answer: Lastname is not mandary - OK
