### ISSUE TITLE
Transactions clickable area is too small

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#665]
## Current Behavior
Open Home tab, move cursor to the transaction area. Cursor changes to a hand and dosent open anything. It will open transaction detail only when you move hand to ">" arrow and click it.
![ClickableAreaTooSmall.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46cb9893208982ab83ec9e51a15cc49b26752a722508e1673295f127b54778154d555ca9485c5643fcfad87eaeb03579de5c0befd73e0b7dc33c45bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e493c1600118cf95a37a28b06.png)

## Acceptiance criteria:
	• When cursor changed to a hand it will open transaction detail if you click it
	• "Hand area" and clickable area is same area

**Comment by RomanShabanov** [comment]
No, the whole area should not be clickable. There will be more elements user can click on.

**Comment by irinadoros** [comment]
Roma, are you sure?
In Android 1.3.4t Beta whole the text is clickable and it opens the transaction details. And arrow area is so small, that it will impossible to click it by finger.

**Comment by fishera123** [comment]
@RomanShabanov I agree with @irinadoros the whole transaction field should be clickable. otherwise, it will be hard for users to open the tx details

**Comment by RomanShabanov** [comment]
I don’t understand. This issue got fixed in the morning and there is a pull request. Why are we still talking about it?

**Comment by RomanShabanov** [comment]
Or was Irina mislead by Lasha’s comment?

**Comment by irinadoros** [comment]
In local branch on Windows it is OK. Clickable area is big.

**Comment by fishera123** [comment]
@irinadoros if it is fixed I will merge

**Comment by irinadoros** [comment]
In windows it is correct now. I can't test it on mobile phone.
