### ISSUE TITLE
Address book doesn't save data when user press [Save] button which is partly visible

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#671]
## Current Behavior
Address book doesn't save data when user press [Save] button which is partly visible. You should press second time for data saving.
If you want to save data with the first click you need to scroll the view as [Save] button is fully visible.

![addressbookaddressexists1](https://user-images.githubusercontent.com/35455231/35157010-55f41d08-fd3b-11e7-8938-56bd98107b72.png)
![addressbookaddressexists2](https://user-images.githubusercontent.com/35455231/35157011-561c7690-fd3b-11e7-9119-e27df358adaf.png)
![addressbookaddressexists3](https://user-images.githubusercontent.com/35455231/35157012-563d1684-fd3b-11e7-9604-db4429688bcd.png)

## Expected Behavior
App should save a contact if data correct or give notification if data are already exists with first click (even [Save] is partly visible).

## Steps to Reproduce (for bugs)
Open app -> click hamburger menu -> click Address Book -> choose new contact with button [+] -> fill the gaps -> press button [Save] if it is partly visible -> button [Save] moves up, but view do nothing -> click second time and app save the content or give the notification

**Environment**
* Windows 10
* 1.4.0

## Acceptance criteria:
* when user press [Save] button in address book which is partly visible, it save the data with first click

**Comment by irinadoros** [comment]
[Save] button is hidden more than in previous relise. Please decrease "Description" field to three rows.

**Comment by msinansahin** [comment]
@irinadoros description length is restricted by 500 characters in new contact. In edit contact if the recorded description is less than it is also restricted by 500, if more than 500 the user is just able to update it can not enter more than what she entered.

And rows are decreased to 3 rows for new contact, 4 for edit contact.

**Comment by irinadoros** [comment]
* 4 rows for edit - OK
* 3 rows for new contact - OK
* 503 characters :) not 500

**Comment by irinadoros** [comment]
When you change existing contact and contact has a long name, then user sees windows scrollbar, not app scrollbar:
<img width="315" alt="contactscrollbar" src="https://user-images.githubusercontent.com/35455231/35669443-cf6a9340-073d-11e8-857f-515b16328446.PNG">

**Comment by irinadoros** [comment]
Scrollbar problem will be fixed in #648
