### ISSUE TITLE
Some views doesn't scroll well on Android - remove scrollbar

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#676]
Lot of app views doesn't scroll by finger well on Android. Like address book, contact view and s.o.

## Current Behavior
For example address book on a phone is not scrollable by finger well in the middle of screen. Sometimes it works, sometimes not. Scroll works well if I use scroll bar on the right part of screen.

![Screenshot_20180122-163140.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791775216455f57821d1b36af3006b1300051bff054a5556f9f08d22a1b63f21df540de4d8395f74c43b42f8b1871eeb13a632c91edbe2e3d7158abd7f37ed998e48341f00198ff95e37a3914bca59f259ac.png)
![Screenshot_20180122-163152.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791775216455f57821d0b16af3006b1300051bff054a5556f9f08d22a1b63f21df540de4d8395f74c43b42f8b1871eeb13a632c91edbe2e3d7158abd7f37ed998e47341f00198ff95e37a39e42ce5bf659ac.png)

With small screen and Android 4.4.2 there is not that problem.

## Your Environment
* Android 7.0
* v1.4.0t Beta

## Expected Behavior
* remove scrollbar from whole app
* User can scroll views by finger everywhere on screen
* Whole app is scrollable well
* It is acceptable if user can't see the scroll, but stil can scroll the page

**Comment by fishera123** [comment]
cannot reproduce

**Comment by irinadoros** [comment]
* remove scrollbar from whole app - OK
* User can scroll views by finger everywhere on screen - OK
* Whole app is scrollable well - OK
* branch **task-676-&-1024** - OK
* Android 7
