### ISSUE TITLE
Address book doesn't controll email format

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#677]
Address book doesn't controll email format.

## Current Behavior
Address book contact view don't do any control to entered email address.
![AddressbookEmailControl.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46c9909e318790ba8de6b0488150f19d2565287d3d16ac2732c9a138ad4d71040c1b5ca6535d5640f5fe8928f7e3347683555fedd16f5927923414adec9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3f18031b8af95f37a7904cda15.PNG)

## Steps to Reproduce (for bugs)
	1. Address book
	2. +
	3. Insert data 
	4. Save

## Your Environment
	• Win 10 devnet
	• Android 7.0
	• V 1.4.0t Beta

## Expected Behavior
	• Check if there @ character
	• Check after @ character if there . character

**Comment by irinadoros** [comment]
The control should apply when focus move away from e-mail address. Now it applies when user insert first letter. - NOK

**Comment by RomanShabanov** [comment]
@irinadoros Actually there has to be no validation for email.  The only validation is required by wallet address, everything else has no business logic. I was the one to introduce the e-mail field, but currently it's not used anywhere. If user decided to save something else inside the email address it is entirely up to him.

**Comment by irinadoros** [comment]
branch-677
The control should apply when focus move away from e-mail address - OK
Control rules is OK as well
