### ISSUE TITLE
End-user can see in which wallet he is operating right now

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#680]
End-user can see in which wallet he is operating right now.

## Current Behavior
If user has a lot of wallets, it is hard to remember or to be 100% sure in which wallet he is operating right now: send dag or delete the wallet. 

![WalletName.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46df95962f8797878ee4ba01e81fe086264c22703d46f96925dcb771e81228000a5748a5480c5f44feffda7fafb33d24984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b0ba834dc8e13821e18a9d02.png)

## Expected Behavior
It would be nice if end-use can see the short name of the wallet.

## Possible Solution
The name field consists of 50 characters. We need to figure out how to show the name and it looks nice in every screen size. We have to decide all views, which will touched by this change.

## Acceptance criteria:
	• End-user easily understands which wallet he is using right now

**Comment by irinadoros** [comment]
* User can see wallet name on wallet delete view, Home, Send, Receive tabs - OK
<img width="642" alt="walletnamevisible" src="https://user-images.githubusercontent.com/35455231/35568373-6c6417b6-05d1-11e8-84b0-92decc741533.png">

**Comment by irinadoros** [comment]
But if the name of a wallet 50 characters as allowed, so it will be moved below the header:
<img width="318" alt="walletlongnamereceive" src="https://user-images.githubusercontent.com/35455231/35569536-0504b630-05d5-11e8-9029-4fa9113a68ed.PNG">

**Comment by irinadoros** [comment]
<img width="954" alt="deletewalletnamevsalias" src="https://user-images.githubusercontent.com/35455231/35666087-5312b6d0-0731-11e8-9164-a6910334a897.png">

**Comment by msinansahin** [comment]
@irinadoros 
When wallet is created 
- walletId
- walletName
named fields are created. If user wants to add an alias for wallet, the alias is connected to walletId field. Wallet name never changes after creating.

**Comment by irinadoros** [comment]
Please lets show only alias. Do now show the name.

**Comment by irinadoros** [comment]
Alias is visible - OK
