### ISSUE TITLE
"Wallet seed not backed up" yellow strip is gone on Chat tab

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#688]
"Wallet seed not backed up" yellow strip is gone on Chat tab. 
Is this required behavior?
	
## Current Behavior
Tabs Home, Receive and Send have yellow strip with warning about back up. Chat tab does not have it.
![PairedDevicesBackup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46d895933187878d8affb640a14ed2952a4d32636b48e13b628ae92dbc56395b4d5a47a8485f5f47adac812dafbf68708a5e0dbe85645a75922f0dbefad341eb5ee779c11ac7a4b6984ec0e23c20e68d884c381a011c8bf85427ed.png)
	
## Expected Behavior
Chat tab has same back up warning on yellow strip

**Comment by fishera123** [comment]
should be visible all over the waller

**Comment by msinansahin** [comment]
@irinadoros @fishera123 
Should the application display the notification on Chat tab? I think that Chat tab is not related with wallet concept, maybe it is hidden because of this reason.

**Comment by fishera123** [comment]
this can be fixed in #648

**Comment by irinadoros** [comment]
Chat tab has same back up warning on yellow strip - OK
