### ISSUE TITLE
App don't do nothing, if click outside of modal window

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#691]
App don't do nothing, if click outside of modal window.

## Current Behavior
Transaction detail and Request specific amount modals have a lot free space for clicking out of modal window. If click it do nothing.
Send tab address book modal do same, but there is not a lot free space.
![ModalClick.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46c59b9e228ea0a586eab401e81fe086264c22703d46f96925dcb771e81228000a5748a5480c5f44feffda7fafb33d24984019af80330b2b9b645bf9fa9015ad00b22a8a4a84b0bb8945c6ea342ce1899d02.png)

## Expected Behavior
When user click out of modal window it should open bottom view. I think, that Send tab address book modal should do same.

## Steps to Reproduce (for bugs)
	• Send -> wallet icon
	• Home -> transaction detail
	• Receive -> request specific amount

## Acceptance criteria:
Click outside of modal window open bottom view

**Comment by msinansahin** [comment]
It is realized that the modal backdrop div is not seen. It maybe about the css classes.

**Comment by irinadoros** [comment]
• Send -> wallet icon - OK
• Home -> transaction detail - OK
• Receive -> request specific amount - OK
* works when user clicks under the modal window; doesn't work, if user clicks on side or up area out of modal - OK
* if user clicks under modal window, but too close to modal window, then back screen will not appear - OK

**Comment by irinadoros** [comment]
* if user clicks under modal window, but too close to modal window, then back screen will not appear  - it is fixed now OK

**Comment by irinadoros** [comment]
if user clicks on side or up area out of modal then background should appear - OK
