### ISSUE TITLE
remove funding node and discovery service support from wallet

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#697]
## Acceptance criteria
* wallet is free from discovery service
* wallet supports new genesis unit
* native currency is DAG

**Comment by irinadoros** [comment]
Notification is not friendly and simply understandable if user don't have enough bytes but have enough dag for paying to merchant.
![merchantinvoicepayment](https://user-images.githubusercontent.com/35455231/36377991-b948f73a-1581-11e8-8dc7-f6d29ba35d3e.png)
