### ISSUE TITLE
Create a database script to make it possible copying the blockchain from an user to another

### ISSUE THREAD

**Issue by uluaiv** [dagcoin/dagcoin#70]

**Comment by yaryribero** [comment]
It is possible to attach a database to another using the attach command (in SQLite):
attach '../.config/dagcoin-faucet-bak/byteball.sqlite' as x;
From then it is possible to make a conditional copy of records from a table in a database to the same in the other one:
insert into main.my_addresses select* from x.my_addresses where x.my_addresses.address not in (select address from main.my_addresses);

**Comment by irinadoros** [comment]
Not actual anymore. Close it.
