### ISSUE TITLE
Android/phone [Back] button doesn't work well

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#704]
Android/phone [Back] button sometime works :) , but 95% of using [back] the app say to me "Press again to exit".
![screenshot_20180124-111928](https://user-images.githubusercontent.com/35455231/35333746-90d5bc0c-0118-11e8-8aed-8ac623f8f37c.png)

## Current Behavior
Move along various screens. Then press phone [back] button. Nothing happen and will be shown notification "Press again to exit".
[Back] works when you open hamburger menu and press [back].

## Your Environment
	• Android 7.0
	• Android 6.0
	• 1.4.0

## Expected Behavior
Phone [back] button brings user to previous view

**Comment by fishera123** [comment]
this is the default behaviour for android
