### ISSUE TITLE
Chat tab remember previosly opened Chat bottom page

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#705]
Chat tab remember previously opened Chat bottom page

## Current Behavior
If user chooses some bottom view from Chat tab, moves to another tab and come back to Chat tab, then app remembers the bottom Chart page - IT IS WRONG. 
![paireddevices](https://user-images.githubusercontent.com/35455231/35335212-8b5097c0-011d-11e8-8d4f-c236986705d6.png)

## Steps to Reproduce (for bugs)
1. Home
2. Chat
3. Add a new device
4. Accept invitation from the other device -> will be shown accept invitation view
5. Home
6. Chat -> will be shown accept invitation view. Instead of that view it should be shown the Chart first view "Paired devices"

## Your Environment
• Win 10
• Android 6.0/7.0
	

## Expected Behavior
• When you switch views, the front page of the view with hamburger menu will always open 
	1. Home
	2. Chat
	3. Add a new device
	4. Accept invitation from the other device -> will be shown accept invitation view
	5. Home
	6. Chat ->  "Paired devices"
            ![chartview](https://user-images.githubusercontent.com/35455231/35335118-3b91bfac-011d-11e8-8336-9bb0eb4beec6.png)

**Comment by irinadoros** [comment]
New contact view is broken:
<img width="319" alt="newcontact" src="https://user-images.githubusercontent.com/35455231/35627687-5b151e16-06a2-11e8-941a-032472752c6c.PNG">

**Comment by irinadoros** [comment]
New contact view is OK now

**Comment by irinadoros** [comment]
Expected behavior is working - OK
1. Home
2. Chat
3. Add a new device
4. Accept invitation from the other device -> will be shown accept invitation view
5. Home
6. Chat -> "Paired devices"

**Comment by msinansahin** [comment]
Fixed in #648 will be removed.
