### ISSUE TITLE
Device paring invitation code copy from QR code doesn't work on PC

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#711]
Device paring invitation code copy from QR code doesn't work on PC
  
## Current Behavior
User create invitation as a QR code for pairing. QR code copy doesn't work if user click on it, but app notify user that data has copied.
With android phone copy functionality works well.
 
![qrinvitationcopy](https://user-images.githubusercontent.com/35455231/35380132-10c434cc-01c1-11e8-8217-6b3180c6908f.png)

## Steps to Reproduce (for bugs)
1.	Open app on the computer
2.	Chat
3.	Add new device
4.	Invite the other device
5.	Click to the QR code -> you see a notification "Copied!"
6.	Open notepad -> you can't paste
7.	Open word -> you can paste, but there is previous data, not invitation code
 
## Your Environment
•	Windows 10
 
 
## Expected Behavior
•	User can copy paring invitation QR code and paste it

**Comment by msinansahin** [comment]
fixed in #task-709

**Comment by irinadoros** [comment]
User can copy paring invitation QR code and paste it - OK
