### ISSUE TITLE
User sees Dagcoin mark in same style in whole application

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#719]
User can see different Dagcoin mark on a different app views. 
Request specific amount view use "DAG". 
Send view use dag icon.

![requestspecificamountdag](https://user-images.githubusercontent.com/35455231/35429557-3c763d92-027d-11e8-9ee7-17950ec8b99d.png)
 
## Steps to Reproduce 
1.	Receive tab -> Request specific amount -> Amount is DAG
2.	Send -> Amount is dag icon
 
## Acceptance criteria:
•	Application use same stile for Dagcoin denote
•	IMHO: dagcoin icon is preferable(!)

**Comment by vkolt** [comment]
When I start to type amount, dagcoin icon is moving up (Mac OS). It shouldn't move
![Screen Shot 2018-02-12 at 21.07.00.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/23a6ea57-0c6b-4ed7-8598-02c0d44388ff)

**Comment by irinadoros** [comment]
* Receive tab -> Request specific amount -> dag icon - OK
* Chat -> some chat -> ... -> request payment -> dag icon - OK

**Comment by irinadoros** [comment]
It is OK in DEVNET
