### ISSUE TITLE
Address book tooltip don't change text according to the cursor location

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#722]
Address book tooltip don't change text according to the cursor location
 
## Steps to Reproduce
Menu -> Address book -> on the red bar is in use tooltip, but it always shows same text "Address book", which is not correct according to cursor location

![newcontactinsert](https://user-images.githubusercontent.com/35455231/35441036-a1c17cb6-02aa-11e8-8f2f-5b1f72d5260e.png)
 
## Your Environment
•	Windows 10
•	Branch: devnet
 
## Acceptance criteria:
•	When cursor locate near the humburger menu, tooltip shows text "Menu"
•	When cursor locate near a "+", tooltip shows text "Create a new contact"
•	When cursor locate in the center of red bar, then user don't see any tooltip

**Comment by iaptsiauri** [comment]
I have changed little bit the wording instead of "Menu" I put "Preferences", imho it is more preferable

**Comment by irinadoros** [comment]
Address book tooltips are nice - OK
Send tab scanner tooltip needs small change.
![sendtooltip](https://user-images.githubusercontent.com/35455231/36299756-375d6f48-1307-11e8-8c82-eb6b48bea5e1.png)

**Comment by irinadoros** [comment]
Send tab scanner tooltip is OK
![image](https://user-images.githubusercontent.com/35455231/36300137-a614a5ae-1308-11e8-9b34-32d20677c208.png)

**Comment by irinadoros** [comment]
In devnet it is OK also
