### ISSUE TITLE
New contact downdrop don't move together with field if app moves

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#723]
New contact downdrop don't move together with field if app moves
 
## Steps to Reproduce
1.	Hamburger menu -> Address Book -> Insert a new contact (+) -> insert new contact data and Save it
2.	Hamburger menu -> Address Book -> Insert a new contact (+) -> insert same name, what you previously inserted -> you will see downdrop with same name -> scroll the app -> downdrop is located in the same place but app is moving

![addressbookdropdown](https://user-images.githubusercontent.com/35455231/35441459-4213a256-02ac-11e8-8659-e526f1059426.png)
 
## Environment
•	Windows 10
•	Branch: devnet
 
## Acceptance criteria:
•	Downdrop should ride with app

**Comment by RomanShabanov** [comment]
@irinadoros this dropdown is rendered by the OS itself, there is no such dropdown in the app.

**Comment by irinadoros** [comment]
Close
