### ISSUE TITLE
User can insert new contact data with length limit 

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#725]
Contact book contact fields has no limitation. 
 
## Steps to Reproduce
Menu -> Address book -> "+" -> fields are not with limited length

![lastnamefieldlimit](https://user-images.githubusercontent.com/35455231/35444344-f1a38c90-02b6-11e8-9857-d7ce742cea88.PNG)
 
## Your Environment
•	Windows 10
•	Branch: devnet
 
## Acceptance criteria:
•	User can not insert more characters than:
Wallet address - 32 characters
First name - 50 characters (now it is 20)
Last name - 50 characters
Email - 254 characters
Description - 300 characters

**Comment by RomanShabanov** [comment]
@irinadoros the address book is stored at the device itself, nothing is ever exchange between device and server/other users. If user wants to create a ridiculous account with foolish data he shall do that by all means. Address book is a syntactic sugar allowing user to map wallet addresses with meaningful information.

**Comment by irinadoros** [comment]
* Send button is not active, when conditions are not met - OK
* Limits are correct - OK
  * Wallet address - 32 characters
  * First name - 50 characters (now it is 20)
  * Last name - 50 characters
  * Email - 254 characters
  * Description - 300 characters

**Comment by irinadoros** [comment]
* Last name field don't have red notification around the box - NOK
<img width="487" alt="newcontactnotifications" src="https://user-images.githubusercontent.com/35455231/36589938-9e122e2a-1895-11e8-91e5-39db66eaa0c5.PNG">

**Comment by irinadoros** [comment]
Validation doesn't work with address and first name during typing (Create new contact). Red notification around the box doesn't come until focus moved away. - NOK
Last name, e-mail, description validation works during typing - OK
<img width="989" alt="newcontactvalidation" src="https://user-images.githubusercontent.com/35455231/36591591-29f7b252-189b-11e8-81cd-5c6c276a2d42.png">

**Comment by irinadoros** [comment]
New contact view validation is correct now - OK
Validation works with all fields - OK
Red notification around box is appeared - OK
Edit contact view is also correct - OK
