### ISSUE TITLE
implement search in address book

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#729]
## Acceptance criteria
* Search field before alphabetic list
* During typing address book sort contacts

**Comment by irinadoros** [comment]
Scrollbar is cutted in address book - NOK
In devnet you can see the nice realization for that.
<img width="989" alt="addressbookscrollbar" src="https://user-images.githubusercontent.com/35455231/36720673-66363e78-1bb1-11e8-9bae-e15fe788d3f9.png">

**Comment by irinadoros** [comment]
New version is much better, but not good enough. Please insert more white space between last name and app window end.
<img width="324" alt="addressbookdesign" src="https://user-images.githubusercontent.com/35455231/36727592-7fe69be6-1bc6-11e8-8749-add5f92c3a68.png">

**Comment by irinadoros** [comment]
Thank you, Eugene! Scrollbar is OK now.
<img width="324" alt="addressboolscrollbar" src="https://user-images.githubusercontent.com/35455231/36729130-c8a710ea-1bcb-11e8-9260-f8175cabcf70.png">
