### ISSUE TITLE
fix eslint errors

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#73]

**Comment by vkolt** [comment]
Clicking to Scan QR code button hang full app

**Comment by fishera123** [comment]
Is there anything else?

**Comment by vkolt** [comment]
still testing

**Comment by vkolt** [comment]
Address receiver and sender is missing sometimes (there should be displayed always the same address)
![Screen Shot 2017-07-11 at 20.41.12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77246455f26b7191a37aef0c2f50415e4cbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc151f142e44853ad14366af43b.png)
