### ISSUE TITLE
add send button in address book contact

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#730]
## Expected Behavior

the user should be able to send the transaction from the address book.

1. Open address book
2. Open contact card 
3. Send button 

## Possible Solution

1. Add send button to address book contact view
2. clicking send button should redirect the user to send view and sender address should be filled with contact address.

**Comment by irinadoros** [comment]
AddressBook contact has a "Send" button - OK
Background of contact view let's do white and add more air between data and [send] button
<img width="989" alt="sendfromcontact" src="https://user-images.githubusercontent.com/35455231/36724120-e083610c-1bba-11e8-8f0b-7c3b83e1442e.png">

**Comment by irinadoros** [comment]
- There is more air between data end [Send] button - OK
- Background is white - OK
- In the bottom of contact view there is some white horizontal bar and [Send] button is hidden under that bar if description is long. There should not be white bar on the bottom. - NOK
<img width="371" alt="contactsend" src="https://user-images.githubusercontent.com/35455231/36730790-54531648-1bd1-11e8-9fe6-8680af254ce7.PNG">

**Comment by irinadoros** [comment]
Visual is correct now - OK
<img width="324" alt="contactview" src="https://user-images.githubusercontent.com/35455231/36785555-e96ff592-1c8b-11e8-861e-22d19f2731c4.png">
