### ISSUE TITLE
implement transaction repetition functionality 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#731]
## Expected Behavior

user should be able to resend transaction from history. 
## Possible Solution

1. add resend button inside transaction details
2. user should be redirected to send page and inputs should be filled with data from transaction details. 

## AS IS:
<img width="314" alt="transactiondetailreceived" src="https://user-images.githubusercontent.com/35455231/37834003-7b68ce52-2eb5-11e8-8393-ac45d6c10310.PNG">

**Comment by rasmusliiva** [comment]
The idea is that the button is showed in transaction details for both incoming and outgoing transactions. If someone sent me money then I can use the button to send him money back. Logic would be same - transaction data would be filled automatically.

![dagcoin_transactiondetails2](https://user-images.githubusercontent.com/37702190/38017766-b055ab70-327b-11e8-9627-a31449641afd.jpg)

**Comment by irinadoros** [comment]
* On Sent transaction details view user sees the button [Make new payment]
* On Pending transaction details view user sees the button [Make new payment]
* On Moved transaction details view user sees the button [Make new payment]
* When user click [Make new payment] from Moved transaction, then receiver address is empty - NOK ?

**Comment by irinadoros** [comment]
Nothing changed:
When user click [Make new payment] from Moved transaction, then receiver address is empty. It should be filled - NOK
