### ISSUE TITLE
Intial run always give an error about dagcoin address correctness

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#733]
Intial run always give an error about dagcoin address correctness.

## Current Behavior
Wallet is created, but app shows error "Incorrect Dagcoin Address"

<img width="322" alt="initialrunrecomended" src="https://user-images.githubusercontent.com/35455231/35501126-a9197f7a-04e1-11e8-8c85-19fd45db69af.png">

## Environment
Branch issue-593
v1.4.0
Windows 10

## Acceptance criteria:
* Wallet is created with correct address

**Comment by fishera123** [comment]
@irinadoros this happens only in debug version
