### ISSUE TITLE
Full wallet initial creation is doesn't work

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#738]
Full wallet initial creation is doesn't work

## Current Behavior
Creating a full wallet with initial run doesn't create full wallet, but light wallet. There is no database sync.

## Steps to Reproduce (for bugs)
Initial run -> Get started -> confirm the terms -> CUSTOM SETTINGS -> DOWNLOAD THE ENTIRE DAGCOIN DATABASE -> enter name of device -> get started ->
	• Created **light wallet**
	• DB is not downloading

## Your Environment
	• Windows 10
	• testnet

## Expected Behavior
* user can create full wallet with initial run according to steps:
Initial run -> Get started -> confirm the terms -> CUSTOM SETTINGS -> DOWNLOAD THE ENTIRE DAGCOIN DATABASE -> enter name of device -> get started

**Comment by msinansahin** [comment]
for initial fresh creation you need to delete or rename the dagcoin-tn folder in your config folder.

**Comment by irinadoros** [comment]
Testnet
1. Go to catalog C:\Users\Irina\AppData\Local
2. Rename folder "dagcoin-tn"
3. Run app with command nw .
4. user can create full wallet with initial run according to steps:
Initial run -> Get started -> confirm the terms -> CUSTOM SETTINGS -> DOWNLOAD THE ENTIRE DAGCOIN DATABASE -> enter name of device -> get started
5. Full wallet is created and database is syncing

**Comment by irinadoros** [comment]
There wasn't a problem. My test was incorrect.
