### ISSUE TITLE
Wallet amount is visible for user even he hasn't logged in yet but clicks [Cancel]

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#743]
Wallet amount is visible for user even he hasn't logged in yet but clicks [Cancel].
Transactions data is also visible for not logged in user..
 
## Steps to Reproduce 
Open Dagcoin app -> pwrd is required -> press [Cancel] button -> app Home view is going darker but user can still see the wallet amount
 
<img width="320" alt="pwrdcancelamount" src="https://user-images.githubusercontent.com/35455231/35516743-3e953278-0515-11e8-9bf2-cf6c6d8d5f4f.PNG">

<img width="335" alt="amountvisiblepwrdrequired" src="https://user-images.githubusercontent.com/35455231/35516749-45484240-0515-11e8-9d86-7810d4f8922c.png">

## Expected Behavior
•	User can not see the wallet amount and transactions data until he is logged in

**Comment by msinansahin** [comment]
@irinadoros I think not balance but transactions should be displayed unless user enters password.

**Comment by irinadoros** [comment]
If amount is decimal number, so the whole amount shpuld be hide, not only integer - NOK
![image](https://user-images.githubusercontent.com/35455231/36026567-6a854f06-0da0-11e8-8359-cd604cc6066b.png)

**Comment by irinadoros** [comment]
Name of the wallet should be hidden as well:
![image](https://user-images.githubusercontent.com/35455231/36027457-fc4f78d2-0da3-11e8-8bb1-90876b969445.png)

**Comment by vkolt** [comment]
1. After creating new wallet user sees empty page, password is not requested. Only possibility to use wallet further is to restart it. (seems password request is missing here)
2. If user try to send coins, password is requested. Cancel password allows user to navigate in app but home page is empty. 
3. Empty home page if user wants to backup wallet but cancel it
4. Empty home page if user wants to switch off password request but cancel it

**Comment by vkolt** [comment]
Address contact couldn't be created
![Screen Shot 2018-02-12 at 21.54.47.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/67e559f2-005c-4a6c-9baf-f1d11bcbd2dd)

**Comment by msinansahin** [comment]
@vkolt can not reproduce "Address contact couldn't be created" error on linux. Could you please test other issues?

**Comment by irinadoros** [comment]
User can not see the wallet amount and transactions data until he is logged in - OK
testnet 1.4.2
issue branch
