### ISSUE TITLE
User sees double bottom menu, if he edits in a Chat tab some conversation settings

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#746]
User sees double bottom menu, if he edits in a Chat tab some conversation settings
  
## Steps to Reproduce 
Chat -> choose conversation with paired device -> Edit -> user can see double bottom menu 

![chatconversationeditmobile](https://user-images.githubusercontent.com/35455231/35563215-b4ed5528-05be-11e8-8b3b-846d3484e5e1.PNG)
<img width="363" alt="chatconversationedit" src="https://user-images.githubusercontent.com/35455231/35563216-b50adb70-05be-11e8-8196-04d2e1d648bf.PNG"> 
## Your Environment
•	1.4.1 testnet
•	Windows 10
•	Android 7.0
 
## Expected Behavior
•	User can see only one bottom menu, if he chooses conversation Edit mode

**Comment by fishera123** [comment]
fixed in #648

**Comment by irinadoros** [comment]
I do not have that problem anymore in branch issue-648 and in the testnet 1.4.1 as well - OK
