### ISSUE TITLE
Send view allow to insert amount with 14 numbers after dot

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#748]
Send view allow to insert amount with 14 numbers after dot and receiver actually will have the rounded amount with 6 numbers after dot. Send view amount should be limited with 6 numbers after dot.

## Steps to Reproduce 
Open wallet -> Send -> insert amount: user can insert number with 14 numbers after dot

<img width="318" alt="sendamountfield" src="https://user-images.githubusercontent.com/35455231/35565049-bf5d53a4-05c4-11e8-91fc-fd36a326068e.PNG">

## Environment
•	1.4.1 testnet
•	Windows 10
•	Android 7.0

## Expected Behavior
•	Send Amount field is limited with six numbers after dot
•	For example 1.456789 – OK
                            1.521478998 - NOK

**Comment by msinansahin** [comment]
Will be fixed in #755

**Comment by irinadoros** [comment]
Send -> Amount -> OK
Request specific amount - OK
