### ISSUE TITLE
Editing of contact in address book crash app on Mac

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#750]
When some existing data of contact is edited, app crashes while saving it

## Expected Behavior

Contact data is saved successfully 

## Current Behavior

Error message: Uncaught exception: TypeError: Cannot read property 'opt' of undefined

## Steps to Reproduce (for bugs)

1. Go to address book
2. Save a contact
3. Edit contact first or last name 
4. Save

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Mac OS High Sierra 10.13.1
* Link to your project:
![Screen Shot 2018-01-30 at 21.02.01.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/f31e0057-4b4c-40e1-8cf5-2102acc15549)

**Comment by dimuha** [comment]
[can not reproduce.zip](https://github.com/dagcoin/dagcoin/files/1720375/can.not.reproduce.zip)
Can not reproduce. Seems it has been fixed somewhere else :)

**Comment by irinadoros** [comment]
On Windows 10 it works; devnet 1.4.3.
