### ISSUE TITLE
Password request crash the app on Mac

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#753]
If password is set error message appears while running the app. Not possible to use app anymore
## Expected Behavior

User should be able to enter password

## Current Behavior

Error message: Uncaught exception: TypeError: Cannot read property 'pub_b64' of undefined

## Steps to Reproduce (for bugs)

1. Set password
2. Close app
3. Open app again
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Mac OS
* Link to your project:

![Screen Shot 2018-01-31 at 20.59.54.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/371564b6-2eda-4957-b334-19c82b50b0cb)

**Comment by dimuha** [comment]
Can not reproduce. @vkolt try to reproduce with a fresh wallet please.

**Comment by vkolt** [comment]
[https://app.zenhub.com/files/94895597/82065597-d790-477a-aef4-d27783ce26bc/download](https://app.zenhub.com/files/94895597/82065597-d790-477a-aef4-d27783ce26bc/download)
