### ISSUE TITLE
User can send DAG amount in format like 012

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#755]
User can send DAG amount in format like 012. Recevier will get 12DAGs :)
 
## Expected Behavior
•	User can not send amount like 012
•	User can send amount like 0.12 or 0,12 or 
 
 
## Steps to Reproduce 
1.Go to send page 
2.Enter not valid amount 01
3.Enter valid address
4.Click send
 
## Your Environment
Testnet 1.4.1
Android 7.0
Windows10

**Comment by msinansahin** [comment]
if the number starts with zero, the "." will be just after the first zero, unless she not used . or , in amount.
Find the possible cases below

01 -> 0.1
000001 -> 0.00001
000.001 ->  0.001

**Comment by msinansahin** [comment]
For decimal character (point and comma) changes according to language of the phone. ?

**Comment by irinadoros** [comment]
I think, that same solution has to be on "Request specific amount" view as well:
<img width="372" alt="requestspecificamount" src="https://user-images.githubusercontent.com/35455231/35981052-fe2c6c0a-0cf4-11e8-98cf-bfa161f6ca55.PNG">

**Comment by irinadoros** [comment]
I still can insert number with two or more dots:
![image](https://user-images.githubusercontent.com/35455231/36026890-a6d434da-0da1-11e8-9e3d-c40ac7883b72.png)

**Comment by irinadoros** [comment]
Solution is working well - OK
Lasha and Sinan and Irina, we decided, that we will not fix multidot problem, because app already has a validation.
