### ISSUE TITLE
User can insert very long number after dot in Request specific amount view

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#756]
User can insert very long number after dot in Request specific amount view.
For example: 5.89741259887777777777779879888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888887777777
Wallet understand, that amount is incorrect, but still it in not user friendly behavior to allow him put such a long number.

![image.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/8f023e51-ff4e-43d1-ad22-7107d0f60ebf)

## Steps to reproduce
Receive -> Request specific amount -> insert the amount

## Acceptance criteria
* User can insert decimal number with 6 numbers after dot
* For example user cannot insert number 1.123456789 -> it should be cut to 1.123456

**Comment by msinansahin** [comment]
will be fixed in #755

**Comment by irinadoros** [comment]
* Receive -> Request specific amount -> insert the amount - OK
* Send -> Amount - OK
