### ISSUE TITLE
"Get started" button missing on some smartphones

### ISSUE THREAD

**Issue by teilolondon** [dagcoin/dagcoin#757]
I'm not working as a programmer, but I found a bug. 

I tried to use the wallet app with a smartphone, that has the resolution 720x1280. It is not possible to use the app, because the "Get started" button is not on the screen. 

![img_20180130_203010](https://user-images.githubusercontent.com/35772448/35750032-457171de-085c-11e8-8d31-82828cf76334.jpg)
![Uploading IMG_20180130_202954.jpg…]()

**Comment by fishera123** [comment]
Hi, thanks for reporting. We will fix it asap.

**Comment by fishera123** [comment]
fixed
