### ISSUE TITLE
Wallet name doesn't fit in menu 

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#758]
Wallet name doesn't fit
## Expected Behavior

* Name is displayed fully in menu
* Name length is limited 50 caracters
## Current Behavior

Name is cut 

## Steps to Reproduce (for bugs)

1. Open menu
2. Click dots in front of wallet name
3. Enter max char allowed
4. Save
5. Check how name looks in menu

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

![IMG_6195.JPG](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/67b11aec-6b62-4baa-9056-13c6aa36be35)

**Comment by irinadoros** [comment]
Name is displayed fully in menu - NOK
Name length is limited 50 characters - OK

![image](https://user-images.githubusercontent.com/35455231/37509494-3d03abec-2900-11e8-8b3f-054fbd5f1ec3.png)

**Comment by irinadoros** [comment]
Name is displayed fully in menu - OK
Name length is limited 50 characters - OK

![image](https://user-images.githubusercontent.com/35455231/37571028-18cfab52-2b00-11e8-9e07-aab384c6624d.png)
