### ISSUE TITLE
Set limit for paired device name

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#759]
Currently there is no limit for paired device name 
## Expected Behavior

Number of characters should be limited - 50 characters
## Current Behavior

Name can be too long, it looks weird on paired devices page
## Steps to Reproduce (for bugs)

1. Pair devises
2. Open chat
3. Click Edit
4. Change wallet name

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

![IMG_6196.JPG](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/7b1ffe2f-641e-4e3e-ba42-5577edcf4248)

**Comment by irinadoros** [comment]
* Limit is 30 characters - OK
* Works on mobile and pc - OK
