### ISSUE TITLE
Save button is half visible when keyboard is open (change device name)

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#761]
## Expected Behavior

Button should be fully visible

## Current Behavior

When keyboard opens, half button is not visible ![IMG_6198.JPG]

## Steps to Reproduce (for bugs)

1. Go to settings
2. Choose System
3. Start to type name
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Android 7.1.1
* Link to your project:

![IMG_6198.JPG](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/15817678-71c5-47d7-8b1c-91059fac6480)

**Comment by irinadoros** [comment]
* When keyboard is appeared, then device name field and button are moving up - OK
