### ISSUE TITLE
 Edit chat page has doubled bottom menu

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#762]
## Steps to Reproduce (for bugs)

1. Pair devices
2. Open chat
3. Click edit
4. Check page bottom

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

![Screen Shot 2018-02-04 at 17.46.16.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/a1ce9133-c754-4faa-910f-ece37990efff)

**Comment by fishera123** [comment]
fixed in #648
