### ISSUE TITLE
User sees wrong tab, if he opens app and chooses pairing device from menu 

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#770]
User sees wrong tab, if he opens app and chooses pairing device from menu 

## Steps to Reproduce 
1. Run app, you are on Home tab
2. Hamburger Menu
3. Pairing device: opened right view but active tab is wrong. It should be Chat, but opened is Home tab

<img width="334" alt="paireddeviceshometab" src="https://user-images.githubusercontent.com/35455231/35851948-2ea1cc0a-0b32-11e8-97ff-45202bb3851d.PNG">
 
## Your Environment
•	Windows 10
•	Android 7.0
•	testnet 1.4.1

## Expected Behavior
•	Chat tab is opened if user choose Pairing device from Menu with app opening

**Comment by vkolt** [comment]
If repeat same case twice, blanc page is shown instead  of pairing devices. Same thing happens from Send and Receive page

![Screen Shot 2018-02-06 at 20.45.22.png](https://images.zenhubusercontent.com/5a6856fb4b5806bc2bc414a1/6cbb6383-4bc5-47c5-bf63-84076f378598)

**Comment by irinadoros** [comment]
With android 7.0 this bug is fixed :) - OK
