### ISSUE TITLE
Amount and address are not prefilled by clicking payment request in chat

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#801]
Payment request in chat is not working as expected. Same with address insert.

## Expected Behavior

After clicking payment request address and amount are filled on Send page

## Current Behavior

All fields stays empty

## Steps to Reproduce (for bugs)

1. Pair devices
2. From one device request some coins
3. On another device go to chat and click payment request
4. Check send page

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Mac OS
* Link to your project:

**Comment by irinadoros** [comment]
Same problem with Windows 10.
On Android amount is filled and receiver address is empty.

**Comment by irinadoros** [comment]
with Windows 10 app in issue branch it is OK
