### ISSUE TITLE
Send all functionality is not working

### ISSUE THREAD

**Issue by vkolt** [dagcoin/dagcoin#802]
Can not send all coins at once

## Expected Behavior

Clicking Send all should prefill amount field with all coins minus fee

## Current Behavior

Send all is not prefill anything
## Steps to Reproduce (for bugs)

1. Go to Send page
2. Click Send all 
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by irinadoros** [comment]
I don't have that problem on Windows 10 testnet 1.4.2:
![sendall2](https://user-images.githubusercontent.com/35455231/36227482-e06fa60c-11d9-11e8-99c6-d1e4edbe6429.png)

**Comment by msinansahin** [comment]
task-797 has also fixed this issue. The reason of errors were same.

**Comment by irinadoros** [comment]
Works on Android and Windows 10 with testnet version.
