### ISSUE TITLE
Icons' service

### ISSUE THREAD

**Issue by RomanShabanov** [dagcoin/dagcoin#82]
There are 2 icons packs in use:
1) Foundation
2) Icomoon

Replace packs with inline svgs and enable grunt svg clean up

**Comment by RomanShabanov** [comment]
https://css-tricks.com/icon-fonts-vs-svg/ - nice article on this topic

**Comment by RomanShabanov** [comment]
Directive is covered with tests as well.

**Comment by yaryribero** [comment]
Merging the changes broke the testnet branch
