### ISSUE TITLE
User can enable only one credential: password OR fingerprint

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#826]
User can use only one identity: password OR fingerprint. But now user can enable both at the same time.

## Steps to reproduce
1. Open app where is login without authorization
2. Go to settings
3. Security
4. Enable scan Fingerprint
5. Touch sensor -> fingerprint is required
6. Click Set password -> app is asking for fingerprint
7. Press Cancel
8. App is asking to set up a password -> repeat it -> both authorization requirements are active
9. You can switch the app and check the security page, you will see that both authorization types are active

![authorizationtype](https://user-images.githubusercontent.com/35455231/36435076-5515f5ea-1669-11e8-8b93-4c2546d92efa.png)

## Environment
* branch 539 with devnet
* Android 7.0

## Acceptance criteria
* Text "Spending restrictions" is replaced. New text should explain that user can choose one of those authorization types
* If user activate another authorization type, the previous one will be automatically switched off

**Comment by fishera123** [comment]
error while creating android package
```Uncaught TypeError: window.plugins.touchid.isAvailable is not a function```

**Comment by irinadoros** [comment]
## Set fingerprint when password is active

1. Go to settings
2. Security
3. Check, that set password option is active
4. Enable option scan Fingerprint 
5. Touch sensor
6. Confirm fingerprint: touch sensor
7. Enter you password for deactivation
**8. Fingerprint authentication ???**
**Expected:** Fingerprint request is set up, password request is switched off
