### ISSUE TITLE
Wallet amount is visible for not logged in user when Fingerprint is required

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#828]
Wallet amount is visible for not logged in user when Fingerprint is required
Transactions data is also visible without autorization.

## Steps to Reproduce 
1. Check in security settings that fingerprint authorization is required
2. Open app: user can see wallet name and transaction data with amount
<img width="1114" alt="authorizationlogin" src="https://user-images.githubusercontent.com/35455231/36479085-fce764a6-170f-11e8-880c-a5ad8847b0b5.png">

## Your Environment
* Android 7.0
* devnet 1.4.3

## Expected Behavior
* User can not see the wallet amount, transactions data and name of the wallet until he is logged in
* Solution is same as for password

**Comment by irinadoros** [comment]
* User can not see the wallet amount, transactions data and name of the wallet until he is logged in with fingerprint - OK
* Solution is same as for password - OK
* password solution still works :) - OK

**Comment by fishera123** [comment]
will merge together with #784
