### ISSUE TITLE
Research: User can export transactions list to CSV on mobile phone

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#834]
User can export transactions list to CSV on mobile phone

## Current behavior
Right now app supports export to CSV only on desktop version. Nowadays mobile phones are so smart, that they can handle with excel as well.

## Steps to Reproduce
1. Home
2. Export to CSV (now you can see it only in desktop version)
![home1 4 0testnet](https://user-images.githubusercontent.com/35455231/36528046-81d433b8-17bc-11e8-8bce-1460954932cb.png)

## Your Environment
* Android

## Expected Behavior
User can export transactions list to CSV on mobile phone

**Comment by msinansahin** [comment]
@irinadoros 
@fishera123                                               
Could not tested on IOS.

**Comment by irinadoros** [comment]
User can export transactions list to CSV on mobile phone - OK
User can open CSV fail on mobile - OK
![excelonphone](https://user-images.githubusercontent.com/35455231/37643960-db7542fe-2c2a-11e8-9367-475614ac6310.jpg)
![exporttocsvmobile](https://user-images.githubusercontent.com/35455231/37643962-db92ed68-2c2a-11e8-9f42-e227a10887c7.jpg)
