### ISSUE TITLE
Multidevice wallet 1-of-2 creation actually create wallet 2-of-2

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#835]
Multidevice wallet 1-of-2 creation actually create wallet 2-of-2

## Steps to Reproduce 
1. Pair devices
2. Add new wallet
3. Multidevice wallet
4. Fill the fields; choose Total number of co-signers 2 and Required number of signatures 1
5. Create 1-of-2 wallet
6. Next view is opened where is header "Waiting for co-signers [2-of-2]"
7. If all devices accept this wallet it would be [2-of-2]  
*QUESTION:* Is it correct or wrong?

![createmultysigwallet1](https://user-images.githubusercontent.com/35455231/36531903-f4391fee-17c7-11e8-984f-10e7c33c0460.png)
![createmultysigwallet2](https://user-images.githubusercontent.com/35455231/36531902-f4169f32-17c7-11e8-9600-d911cff15911.png)
![createmultysigwallet3](https://user-images.githubusercontent.com/35455231/36531904-f45e0296-17c7-11e8-8dae-3f9d99f7ab1b.png)

## Your Environment
devnet 1.4.3

## Expected Behavior
User can create multidevice wallet 1-of-2

**Comment by irinadoros** [comment]
![multidevice](https://user-images.githubusercontent.com/35455231/37408595-17b4e2ae-27a5-11e8-8827-fcaa14c53d14.PNG)

**Comment by irinadoros** [comment]
in Dagcoin app I create wallet with 3 co-signers and 1 required signature and created wallet is 1-of-3 - OK
![image](https://user-images.githubusercontent.com/35455231/37571256-fc0f6928-2b02-11e8-8081-cfe52e0abc9d.png)

**Comment by c0b333r** [comment]
I'm getting error: "Could not create payment proposal: authentifier verification failed"
How to fix it?
Multidevice wallet
