### ISSUE TITLE
gap between transaction list and show history button is big 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#85]
![screen shot 2017-07-13 at 10 23 19 am](https://user-images.githubusercontent.com/9304560/28155033-6b371948-67b5-11e7-9ba1-b1db72042631.png)

**Comment by vkolt** [comment]
What is the expected result? Right now this button is located on the bottom of page as footer. And this footer takes half of the screen

**Comment by fishera123** [comment]
the expected result as it says it that gap should be smaller then it is now.
