### ISSUE TITLE
implement session log

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#852]
Session log should monitor all the important activities of wallet that might be useful for fixing support cases. 
User should be able to:
* filter session logs into different types: debug, info, error or all together. 
* copy it to clipboard
* send it to support on the mail
* default log level type: all together

**Comment by irinadoros** [comment]
On PC user can see one second "Send by email" possibility and after 1 second it is gone - NOK 
<img width="649" alt="sessionlogpc" src="https://user-images.githubusercontent.com/35455231/38485704-6a3050ac-3be3-11e8-9db6-d31330b0fcb7.png">

**Comment by irinadoros** [comment]
The receiver address should be empty. On PC user can see abc@com - NOK
