### ISSUE TITLE
Recovery from seed works with javascript error 

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#882]
Recovery from seed works with javascript error but recover the funds.

## Steps to Reproduce
0. Use phone for testing
1. Initial run 
2. Get some DAG
3. Delete seed words (save it before)
4. Do full back up
5. Initial run 
6. Recover from seed
7. Recovery is successfully completed, restart is needed
8. Open Dagcoin app: javascript error

## Your Environment
* Android 7.0

![Rec2.jpg](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/92a0d781-fa98-4708-b2bd-35be1b937423)

## Expected Behavior
* Research: what is the cause of the problem?!
* User can recover his funds with seed
* flow works well and don't have errors

**Comment by irinadoros** [comment]
In refactor branch there is no same error. Will not spent time on this problem in testnet.

**Comment by fishera123** [comment]
have to ask about this in byteball community
