### ISSUE TITLE
User cannot pair devices 

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#883]
User cannot pair devices. 
First device, witch scanned the invitation QR code, shows the chat and user can write a message, but sending doesn't work.
On the second device still user can see the invitation QR code.

## Steps to Reproduce
1. Go to paired devices page
2. Click add device
3. Choose Invite other device
4. On another device choose Accept invitation 
6. Scan invitation QR code
**Expected:** devices are paired and chat appears 

## Environment
* devnet + devnet -> doesn't work
* devnet + 1.4.0 (1.4.1) -> pair well

## Expected Behavior
* devices are paired and chat appears on both devices
* devices can send messages to each other

**Comment by fishera123** [comment]
cannot reporduce, tried several times and it works

**Comment by irinadoros** [comment]
Functionality works well. It seems that problem was with wrong installed application. Close ticket.
