### ISSUE TITLE
Bug fixes and and new developments  in refactor branch

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#885]
1. In Request specific amount modal, share link is absent.  **This is not a bug.**

3. Application successfully updated, please restart the application. warning **Not reproducable**

4. When create new wallet, creating wallet message remains on screen.

5. According to 5, first creation wallet phase is broken. 

6. While wallet is sending transction mode, as trying to send transaction "Could not send payment: Not enough dagcoins" message appears.

* Transaction link must be changed as "https://testnetexplorer.byteball.org" **No need**

**Comment by msinansahin** [comment]
This is followed in refactor branch.

**Comment by fishera123** [comment]
started in #617

**Comment by fishera123** [comment]
Please consider moving transaction list and bottom menu as a directive. Also, move modals outside of controllers.

**Comment by fishera123** [comment]
move service methods from controller to services

**Comment by fishera123** [comment]
consider changing index.event.support.js with some other solution

**Comment by msinansahin** [comment]
-In Request specific amount modal, share link is absent. This is not an issue. It was a feature just on phones. It is OK on phones in refactor.
