### ISSUE TITLE
Auto-fill possibility is available on seed recovery field

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#887]
Auto-fill possibility is available on seed recovery field. Previously auto-fill functionality wasn't available. It should be switched off.

## Steps to Reproduce (for bugs)
1. Open app
2. Go to Settings
3. Open Security
4. Recover wallet
5. Long press to "Your wallet seed" field -> phone shows two possibility "Paste  |  Auto-fill" - there should be only one choice "Paste"

![autofill](https://user-images.githubusercontent.com/35455231/37331103-a2f53cba-26ab-11e8-9ea7-4ade363c27a9.jpg)

## Your Environment
Android 7.0
devnet

## Expected Behavior
* When user click field "Your wallet seed", then android allow only paste the data from memory
* Auto-fill choice is not available

**Comment by dkostenevich** [comment]
I can't reproduce this issue on my phone.

**Comment by irinadoros** [comment]
Needs to be checked with android 7 or older.
Hypothesis: may be this behavior is regarding to Android 8.0

**Comment by irinadoros** [comment]
![android7](https://user-images.githubusercontent.com/35455231/37585994-af278f80-2b63-11e8-95ea-f0ddf2500d71.jpg)

Hypothesis is confirmed. With Android 7 there is no Autofill field.
