### ISSUE TITLE
Wallet user can't send his address or request some payment via chat

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#917]
Wallet user can't send his address or request some payment via chat.
User can see the links from [+] button as "Insert my address" and "Request payment", but they doesn't do anything.

## Steps to Reproduce (for bugs)
1. pair devices
2. open chat
3. choose some chat
4. press [+] button
5. choose "Insert my address" -> nothing happen
6. choose "Request payment" ->  nothing happen

![RefactorPairedInsertMyAddress.PNG](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/e996708d-7c3b-4926-b189-103d0cf3dd9b)

## Your Environment
* Windows 10
* **refactor**

## Expected Behavior
* User can send his wallet address via chat
* User can request a payment via chat

**Comment by msinansahin** [comment]
@fishera123 @irinadoros 
Must Previous messages be thought?

Previous paymentRequestRegexp 
/\[.*?\]\(byteball:([0-9A-Z]{32})\?([\w=&;+%]+)\)/g

Current paymentRequestRegexp
/\[.*?\]\(Dagcoin:([0-9A-Z]{32})\?([\w=&;+%]+)\)/g

**Comment by irinadoros** [comment]
Cannot reproduce it anymore. It is fixed now in refactor branch.
