### ISSUE TITLE
Message sending doesn't work with [Enter] button in Chat page

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#918]
Message sending doesn't work with [Enter] button in Chat page.

## Steps to Reproduce 
1. Pair devices
2. Open some chat
3. write some message to the box
4. press [Enter] -> row is changed, but it should send a message - NOK
5. press "paper plane" icon -> message will be sent out

![image.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/b8cbd94a-41f2-424e-b08b-e6db20aa5b84)

## Your Environment
* windows 10
* refactor branch

## Expected Behavior
* when user write a text in chat and press [Enter], text is sent out
* when user write a text in chat and press [Enter+Shift], cursor is changed row and user can write text on next row

**Comment by irinadoros** [comment]
* when user write a text in chat and press [Enter], text is sent out - OK
* when user write a text in chat and press [Enter+Shift], cursor is changed row and user can write text on next row - NOK Now textis sent out - this is wrong.

**Comment by msinansahin** [comment]
Fixed in refactor.

**Comment by irinadoros** [comment]
when user write a text in chat and press [Enter], text is sent out - OK
when user write a text in chat and press [Enter+Shift], cursor is changed row and user can write text on next row - OK
