### ISSUE TITLE
QR code scanning doesn't work: "Incorrect Dagcoin Address"

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#924]
QR code scanning doesn't work. App answer "Incorrect Dagcoin Address".
BUT it works with Testnet DAG QR code. For example user can scan with refactor branch wallet QR code of Testnet Dag wallet and it will works well.

## Steps to Reproduce
1. Open refactor branch wallet
2. Open Send
3. Click "Scan address"
4. Show the QR code from another device with refactor branch ->  "Incorrect Dagcoin Address" - NOK
4.1 4. Show the QR code from another device with testnet branch -> address is correct and user can send money - NOK

## Your Environment
* refactor
* Windows 10

## Expected Behavior
* Only refactor branch wallet addresses are correct in refactor branch
* testnet or livenet addresses are not acceptable in refactor branch

**Comment by msinansahin** [comment]
Comitted to refactor branch. Test via refactor brach.

**Comment by irinadoros** [comment]
* User insert testnet address -> refactor branch app doesn't notify, that address is not correct - NOK
