### ISSUE TITLE
User can't see wich chat has a new message

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#927]
User can't see wich chat has a new message. User can see the notification on CHAT bottom menu, but notification is not visible in chats list on some specified chat.

## Steps to Reproduce
1. Pair devices
2. Close chat on one device
3. Send message from second device to first device 
4. Check first device Chat page

![ChatMessagesRefactorMobile.jpg](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/7749a651-b2e3-47c0-986b-7ae11d58dd0b)

## Your Environment
* Android 8.0
* Windows 10 
* refactor

## Expected Behavior
* If user has new messages, then notification is visible in chat list also
* works like in testnet (look a picture)

**Comment by msinansahin** [comment]
Committed into refactor branch. Test via refactor branch.

**Comment by irinadoros** [comment]
* If user has new messages, then notification is visible in chat list also - OK
* works like in testnet (look a picture) - OK
