### ISSUE TITLE
Notification bar is misplaced 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#937]
## Expected Behavior

* there shouldn't be a gap between notification bar and backup bar. 
* animation should stay as it is in testnet

## Current Behavior

![image](https://user-images.githubusercontent.com/9304560/37719530-eaf2fa7e-2d2d-11e8-80ea-69bee3853452.png)

## Steps to Reproduce (for bugs)

1. Make any action which will show nofitication bar as a result(for example create new wallet)

**Comment by irinadoros** [comment]
Notification place is changed - OK
<img width="319" alt="notificationasukoht png" src="https://user-images.githubusercontent.com/35455231/37893420-9fcc56b2-30e3-11e8-9c7f-6e9f91d8b48f.png">
