### ISSUE TITLE
In case user doesn't have coin and transaction history the link where user can buy coins

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#939]
## Expected Behavior

user should see two buttons "buy dagcoins" and "show dagcoin address" (?) in transaction list and send page, if user doesn't yet purchased coins before. 

## Current Behavior

currently in home page "no transactions" is display and on send page form which is useless. 

## Possible Solution

example design for implementation:
![buydagcoin](https://user-images.githubusercontent.com/35455231/37834270-0c99ee9c-2eb6-11e8-8a07-fe32a8a063b9.png)

**Comment by rasmusliiva** [comment]
![dagcoin_buy](https://user-images.githubusercontent.com/37702190/37969905-add7b5e2-31da-11e8-8713-30e4110ae695.jpg)
![dagcoin_buy2](https://user-images.githubusercontent.com/37702190/37969906-adf765a4-31da-11e8-997f-f6631f549218.jpg)

**Comment by irinadoros** [comment]
Irina, add URL please!!!

**Comment by irinadoros** [comment]
Link: https://daguniversity.com/en

**Comment by irinadoros** [comment]
* local branch - OK
* If user doesn't have any transaction and amount is zero, then he can see the view "Start sending Dagcoin" - OK
* Button [Buy dagcoin] redirects user to url https://daguniversity.com/en - OK
* Link "Show wallet address" redirects to the Receive page - OK

![image](https://user-images.githubusercontent.com/35455231/39044473-e4758f4a-4498-11e8-872b-eed25d8f1562.png)
