### ISSUE TITLE
Chatbot for the faucet

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#94]

**Comment by fishera123** [comment]
@vkolt this task should be tested with #100 task.

**Comment by vkolt** [comment]
Sending address give not correct message and error at exit
1. Insert my address  from one device 
2. Check message on another (message itself does not look correct)
3. Offer a contract link gives error
4. Close chatbot (this action gives error)

**Comment by VikaMarkowa** [comment]
![Screenshot (7).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/594bd850ce45e0002021a000/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ab9d665043761260ea62864c7b96aea1b2f58585f4dfd1450594df5ad892ba4b06f2483590ab9c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0e13f26e088874b37191755.png)

**Comment by vkolt** [comment]
![Screenshot (7).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0ab9d665043761260ea62864c7b96aea1b2f58585f4dfd1450594df5ad892ba4b06f2483590ab9c3714d36976345f3e5db55ea43a82a994d83bcbd8f4cc0e13f21e3828749361b1755.png)

**Comment by vkolt** [comment]
byteball.org inside paring link

**Comment by vkolt** [comment]
Request a payment functionality gives error and closes application

**Comment by vkolt** [comment]
Old link for paring can be used after deleting device
