### ISSUE TITLE
add square in qr code scanner

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#941]
## Expected Behavior

user should see the squar where he/she can put the  qr code.
## Current Behavior

Currently it is just plain screen and users have to guess where to put qr code in order to be scanned.
## Possible Solution

Possible design:
https://files.slack.com/files-pri/T5CRRQBNK-F9TL9V50U/screen_shot_2018-03-01_at_10.09.23_am.png

**Comment by msinansahin** [comment]
It is created against the refactor branch.

**Comment by irinadoros** [comment]
Please merge it into refactor also.
Tested in branch task-941 with Windows 10 - OK
![image](https://user-images.githubusercontent.com/35455231/38243817-64bc9064-3741-11e8-9bef-626dd8d90259.png)
