### ISSUE TITLE
The sending amount in notification text is wrong

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#950]
User has not enough dags for sending, but still try to send the bigger amount. Notification appear - OK
The amount in notification is wrong - NOK

## Steps to Reproduce
* User has 3 wallet addresses (for example)
* All 3 wallet addresses has some money
* User send more money out than he has
* Notification appear, but the amount in text is wrong - NOK

![NotEnoughMoneyRefactor.PNG](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/ee96d900-0549-4ff2-a517-6468fee32275)

## Your Environment
* Android 8.0
* Windows 10
* Refactor

## Expected Behavior
* The amount in notification is changed in case if user send more money than he has.

**Comment by msinansahin** [comment]
@irinadoros                        
Converted error message to "Not enough spendable funds".
Removed funds amount from message.
Test via this task-950

**Comment by irinadoros** [comment]
Message is "Not enough spendable funds" - OK
![image](https://user-images.githubusercontent.com/35455231/37815633-5454c8bc-2e78-11e8-8c91-9b303b36899a.png)

**Comment by irinadoros** [comment]
@fishera123 , please add to refactor branch
