### ISSUE TITLE
Asking for Fingerprint credentials

### ISSUE THREAD

**Issue by dannybreal** [dagcoin/dagcoin#96]
## Current behavior:
Right now user can only set password.   
 
## Expected behavior:
* We should enable possibility for users to set password OR fingerprint
* Works on mobile device

**Comment by irinadoros** [comment]
* Login with fingerprint - OK
* Login with phone secure code - OK
* 5 times user can insert wrong fingerprint and after that phone/app asks for phone secure code - OK
* Send page asks for fingerprint and [Send] button click - OK
