### ISSUE TITLE
User can see empty app page, when he uses Android back button

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#963]
When user use on Andorid phone Back button, then Dag app shows white empty screen

## Steps to Reproduce
1. Open app on Android phone with Home page
2. Go to Receive page for example
3. Press [Back] button on phone 
Expected: Home page is open.
AS IS: App has bottom menu end header and no data in the middle

![Screenshot_20180323-102903.jpg](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/f95c852a-79c2-4a00-9d34-4c88f167a080)

![screenshot_20180323-102909](https://user-images.githubusercontent.com/35455231/37819334-cd6c61c6-2e85-11e8-8619-9edf775746a9.jpg)

## Your Environment
* refactor
* Android 8.0

## Expected Behavior
* When user press phone [Back] button, then he can see previous app page

**Comment by msinansahin** [comment]
Added "source" property state. Controlling this property in back() method like parent property.
