### ISSUE TITLE
Bottom menu redesign

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#969]
Bottom menu redesign

## Expected Behavior
* Received page icon is changed. Now it is thicker than another icons. It should be in same style with bottom menu icons
* Icons and name of the icons have some space between 
 Paired device icon is twisted  (now it is up side down)

![BottomMenu.png](https://images.zenhubusercontent.com/5a5caf284b5806bc2bc2c5cf/71b2688b-2251-463c-b747-e970d435af66)

**Comment by msinansahin** [comment]
Fixed in refactor branch.

**Comment by irinadoros** [comment]
![image](https://user-images.githubusercontent.com/35455231/37838601-036f5e00-2ec1-11e8-809e-e8f62d44c29c.png)
