### ISSUE TITLE
Explorer doesn't show transactions

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#974]
Forked Explorer doesn't show transactions

## Expected Behavior
* Forked Explorer shows transactions

**Comment by uluaiv** [comment]
It's a nginx configuration problem.
See:
https://stackoverflow.com/questions/25896225/how-do-i-get-socket-io-running-for-a-subdirectory

**Comment by irinadoros** [comment]
Forked Explorer shows transactions - OK
