### ISSUE TITLE
Share icon is missing in the header of the Receive page

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#979]
Share icon is missing in the header of the Receive page

![receivepage](https://user-images.githubusercontent.com/35455231/37970357-efb35fec-31db-11e8-92ed-4ff2af9a7708.jpg)

## Your Environment
* **Refactor branch**
* **testnet**
* Windows 10
* Android 8.0

## Expected Behavior
* Share icon is visible in the header of the Receive page

**Comment by msinansahin** [comment]
This issue is related to refactor branch. It was fixed in refactor.

**Comment by irinadoros** [comment]
Share icon is visible in the header of the Receive page on mobile phone - OK
This icon is not visible on PC - OK
![receivepage2](https://user-images.githubusercontent.com/35455231/38079059-cffdb7da-3346-11e8-80db-c5ad84f689ed.jpg)
