### ISSUE TITLE
Change Cordova Gradle dependency configuration in build.gradle for Android

### ISSUE THREAD

**Issue by sabahang** [dagcoin/dagcoin#982]
## Expected Behavior
Gradle Sync should succeed 

## Current Behavior
Gradle Sync fails with following errors:
Unable to resolve dependency for ':@debug/compileClasspath': Could not resolve project :CordovaLib.

Could not resolve project :CordovaLib.
Required by:
    project :
 > Project : declares a dependency from configuration 'debugCompile' to configuration 'debug' which is not declared in the descriptor for project :CordovaLib.

## Steps to Reproduce (for bugs)
Opening the project in Android Studio and trying to sync gradle build files

## Context
Have to manually change settings every time

## Related Info:
https://stackoverflow.com/questions/47023068/unable-to-run-ionic-app-after-update-to-android-studio-3-0
https://issues.apache.org/jira/browse/CB-11244

**Comment by sabahang** [comment]
@fishera123 I couldn't find a way to fix this except for upgrading cordova to version 7 or above. Don't want to spend too much time on it unless justified

**Comment by fishera123** [comment]
@sabahang which version of cordova fixes this?
