### ISSUE TITLE
Initial run give an exception

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#983]
Initial run give an exception: "An e xception occurred: Error: configService#getSync called when cache is not initialized; cause: undefined"

## Current Behavior
* App is down load, user open it and some time later error appears

## Steps to Reproduce (for bugs)
1. Initial run
2. Wait some time..

![initialrunexeptiontestnet](https://user-images.githubusercontent.com/35455231/38024859-ef1bfaf4-328e-11e8-9ccd-ee6cdcd6f7f7.png)

## Your Environment
Android

## Expected Behavior
* User can download app and start it normally

**Comment by fishera123** [comment]
fixed in testnet

**Comment by irinadoros** [comment]
Tested in testnet with Android 8.0 and Windows 10: 
User can download app and start it normally - OK

**Comment by irinadoros** [comment]
Anroid 8.0 testnet branch - OK
