### ISSUE TITLE
Create context in testnetexplorer.dagcoin.org as "/paymentRequest"

### ISSUE THREAD

**Issue by msinansahin** [dagcoin/dagcoin#992]
Create context in testnetexplorer.dagcoin.org as "testnetexplorer.dagcoin.org/paymentRequest"

## Expected Behavior
This *https://testnetexplorer.dagcoin.org/paymentRequest* context must response to the clients with GET method. This url will have two parameters: amount and address such as https://testnetexplorer.dagcoin.org/paymentRequest?amount=111&address=SFSDFSDFSDF. 
So that, server have to response dynamically.

**Comment by msinansahin** [comment]
It is related to #881

**Comment by irinadoros** [comment]
Testnetexplorer.dagcoin.org as "/paymentRequest" is created:
![screenshot_20180404-162443](https://user-images.githubusercontent.com/35455231/38311230-59e7e044-3827-11e8-8408-ab49217ceaa2.jpg)
